apiVersion: v1
kind: ConfigMap
metadata:
    name: airflow-scheduler
    namespace: hsg-data-labs-dev
data:
    AIRFLOW_HOME: /airflow
    AIRFLOW_GPL_UNIDECODE: "yes"
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    # AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "True"
    AIRFLOW__CORE__FERNET_KEY: yTUPS9onxDd2OdQCS8VGqJgpLsg4WaK4WPDIb5teAJQ=
    AIRFLOW__CORE__HOSTNAME_CALLABLE: socket:gethostname
    AIRFLOW__CORE__DEFAULT_IMPERSONATION: "1000280000"
    AIRFLOW__WEBSERVER__RBAC: "True"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: Source/Python/datalabs/dag
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
    AIRFLOW__KUBERNETES__NAMESPACE: hsg-data-labs-dev
    AIRFLOW__KUBERNETES__IN_CLUSTER: "True"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
    AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: /airflow/worker.yaml
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: apache/airflow
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: master-python3.7
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: IfNotPresent
    # AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: default
    AIRFLOW__KUBERNETES__FS_GROUP: "1000280000"         # Allowed Range: 1000280000, 1000289999
    AIRFLOW__KUBERNETES__RUN_AS_USER: "1000280000"      # Allowed Range: 1000280000, 1000289999
    # AIRFLOW__KUBERNETES__GIT_SYNC_CONTAINER_REPOSITORY: harbor.ama-assn.org/hsg-data-labs/git-sync
    # AIRFLOW__KUBERNETES__GIT_SYNC_CONTAINER_TAG: 1.0.0
    # AIRFLOW__KUBERNETES__GIT_SYNC_RUN_AS_USER: "1000280000"
    # AIRFLOW__KUBERNETES__GIT_SYNC_FS_GROUP: "1000280000"
    # AIRFLOW__KUBERNETES__GIT_REPO: git@bitbucket.org:hsdatalabs/hsg-data-labs.git
    # AIRFLOW__KUBERNETES__GIT_BRANCH: master
    # AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: /tmp/dags
    # AIRFLOW__KUBERNETES__GIT_SYNC_ROOT: /tmp/git
    # AIRFLOW__KUBERNETES__GIT_SYNC_DEST: hsg-data-labs
    # AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: git-sync
    # # AIRFLOW__KUBERNETES__GIT_SYNC_SSH_SECRET_VOLUME_NAME: bitbucketprd
    # # AIRFLOW__KUBERNETES__GIT_SYNC_CREDENTIALS_SECRET: git-sync-harbor
