apiVersion: v1
kind: ConfigMap
metadata:
    name: airflow-scheduler
    namespace: hsg-data-labs-dev
data:
    AIRFLOW_HOME: /airflow
    AIRFLOW_GPL_UNIDECODE: "yes"
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__FERNET_KEY: yTUPS9onxDd2OdQCS8VGqJgpLsg4WaK4WPDIb5teAJQ=
    AIRFLOW__WEBSERVER__RBAC: "True"
    AIRFLOW__KUBERNETES__GIT_REPO: git@bitbucket.org:hsdatalabs/hsg-data-labs.git
    AIRFLOW__KUBERNETES__GIT_BRANCH: master
    AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: ./airflow/dags
    AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: Source/Python/datalabs/dag
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
    AIRFLOW__KUBERNETES__NAMESPACE: hsg-data-labs-dev
    AIRFLOW__KUBERNETES__IN_CLUSTER: "True"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
    AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: airflow
    AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: bitbucketprd
    # KUBECONFIG: /airflow/kubeconfig
