apiVersion: v1
kind: ConfigMap
metadata:
    name: airflow-webserver
    namespace: hsg-data-labs-dev
data:
    AIRFLOW_HOME: /home/airflow
    AIRFLOW_GPL_UNIDECODE: "yes"
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__FERNET_KEY: yTUPS9onxDd2OdQCS8VGqJgpLsg4WaK4WPDIb5teAJQ=
    AIRFLOW__CORE__HOSTNAME_CALLABLE: socket.gethostname
    AIRFLOW__WEBSERVER__RBAC: "True"
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "true"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: Source/Python/datalabs/dag
