med_words =  [
    ' md',
    ' med ', 
    ' dr', 
    ' m d',
    "dr", 
    "pharmac", 
    'allergy', 
    'ambulance',
    'anesthesi',
    'cancer', 
    'cardio',
    'care center', 
    'chiropract', 
    'clinic', 
    'dentist', 
    'dermatology',
    'diagnostic',
    'disease', 
    'doctor',
    'emergency',  
    'endocrinolog',
    'facs',
    'family care', 
    'family practice',
    'gastroent',
    'glaucoma',
    'health', 
    'hlth', 
    'hosp', 
    'kidney', 
    'm.d.',
    'md', 
    'medic',
    'mri', 
    'neurology', 
    'ob gyn',
    'obgyn',
    'oncology',
    'operation', 
    'orthopaedics',
    'orthope', 
    'patholog',
    'patient',
    'pediatric', 
    'perioperative', 
    'physician',
    'primary care',
    'psych',  
    'pulmonary', 
    'radiolog',
    'surgeon',
    'surgery',
    'surgical', 
    'throat', 
    'urgent care', 
    'urology',
    'vascular', 
    'vein', 
]