# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.9
        args: [-l 120]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black-jupyter
        language_version: python3.9
        args: [-l 120]
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8
  #       args: [--max-line-length=120]
  #       verbose: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        verbose: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: check-added-large-files
        stages: [commit]
        args: ["--maxkb=10240"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: run.py
        language: system
        types: [python]
        args: ["pylint", "--extension-pkg-whitelist=pyodbc, numpy, math"]
        stages: [push]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./Script/run_unit_tests.sh
        language: system
        stages: [push]
