image: gradle:6.7.0-jre14

pipelines:
    branches:
        master:
        - step:
            script:
            - ./Script/bitbucket-pipelines-build
              variables:
                  BUTBUCKET_USER: $BUTBUCKET_USER
                  BUTBUCKET_USER: $BITBUCKET_PASSWORD
    custom:
        Test:
        - step:
            name: Unit Tests
            script: make test
        - step:
            name: Lint
            script: make lint
