image: muffinspawn/pipelines:3

pipelines:
    branches:
        master:
        - step:
            script:
            - bash Script/bitbucket-pipelines-build.sh
        dev:
        - step:
            script:
            - bash Script/bitbucket-pipelines-build.sh
        test:
        - step:
            script:
            - bash Script/bitbucket-pipelines-build.sh
        stage:
        - step:
            script:
            - bash Script/bitbucket-pipelines-build.sh
        prod:
        - step:
            script:
            - bash Script/bitbucket-pipelines-build.sh
    custom:
        Test:
        - step:
            name: Master Virtual Environment
            caches:
              - venv
            script:
            - bash Script/setup-virtual-environment Master
        - parallel:
            - step:
                name: Unit Tests
                caches:
                  - venv
                script:
                - export VIRTUAL_ENV=${PWD}/Environment/Master
                - export PATH="$VIRTUAL_ENV/bin:$PATH"
                - python Script/run.py python -m pytest Test/Python/ Test/Python/test/datalabs/build/ -W ignore::DeprecationWarning
            - step:
                name: Lint
                caches:
                  - venv
                script:
                - export VIRTUAL_ENV=${PWD}/Environment/Master
                - export PATH="$VIRTUAL_ENV/bin:$PATH"
                - python Script/run.py pylint --extension-pkg-whitelist=pyodbc,numpy ${PWD}/Source/Python/datalabs/* ${PWD}/Test/Python/test/datalabs/*
        CPT-master:
        - step:
            name: Update Bundle
            script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION='us-east-1'
            - export AWS_S3_BUCKET='ama-hsg-datalabs-lambda-code-sandbox'
            - bash Deploy/CPT/create-bundle
            - bash Deploy/CPT/upload-bundle
        - step:
            name: Update Lambda Functions
            script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION='us-east-1'
            - bash Deploy/CPT/update-functions
        CPT-dev:
        - step:
            name: Placeholder
            script:
            - echo "Hello there!"
definitions:
  caches:
    venv: Environment
