image: gradle:6.7.0-jre14

pipelines:
    branches:
        master:
        - step:
            script:
            - export BUTBUCKET_USER=$BUTBUCKET_USER
            - export BITBUCKET_PASSWORD=$BITBUCKET_PASSWORD
            - bash Script/bitbucket-pipelines-build.sh
    custom:
        Test:
        - step:
            name: Unit Tests
            script:
            - make test
        - step:
            name: Lint
            script:
            - make lint
