image: muffinspawn/pipelines:3

pipelines:
    branches:
        master:
        - step:
            script:
            - bash Script/bitbucket-pipelines-build.sh
        dev:
        - step:
            script:
            - bash Script/bitbucket-pipelines-build.sh
        test:
        - step:
            script:
            - bash Script/bitbucket-pipelines-build.sh
        stage:
        - step:
            script:
            - bash Script/bitbucket-pipelines-build.sh
        prod:
        - step:
            script:
            - bash Script/bitbucket-pipelines-build.sh
    custom:
        Test:
        - step:
            name: Unit Tests
            script:
            - bash Script/setup-virtual-environment Master
            - export VIRTUAL_ENV=${PWD}/Environment/Master
            - export PATH="$VIRTUAL_ENV/bin:$PATH"
            - ${PWD}/Script/run.py python -m pytest Test/Python/ Test/Python/test/datalabs/build/ -W ignore::DeprecationWarning
        - step:
            name: Lint
            script:
            - bash Script/setup-virtual-environment Master
            - export VIRTUAL_ENV=${PWD}/Environment/Master
            - export PATH="$VIRTUAL_ENV/bin:$PATH"
            - ./Script/run.py pylint --extension-pkg-whitelist=pyodbc,numpy ${PWD}/Source/Python/datalabs/* ${PWD}/Test/Python/test/datalabs/*
        CPT:
        - step:
            name: Build Bundle
            script:
            - bash Script/setup-virtual-environment Master
            - export VIRTUAL_ENV=${PWD}/Environment/Master
            - export PATH="$VIRTUAL_ENV/bin:$PATH"
            - ${PWD}/Script/bundle-project CPT
        - step:
            name: Upload Bundle
        - step:
            name: Update Lambda Functions
