image: muffinspawn/pipelines:1

pipelines:
    branches:
        master:
        - step:
            script:
            - echo $TEST_EM_MY_VARIABLE
            - echo $BITBUCKET_USER
            - echo $BITBUCKET_PASSWORD
            - printenv
            - bash Script/bitbucket-pipelines-build.sh
    custom:
        Test:
        - step:
            name: Unit Tests
            script:
            - export VIRTUAL_ENV=/Build/Environment/Master
            - export PATH="$VIRTUAL_ENV/bin:$PATH"
            - ./Script/run.py python -m pytest Test/Python/ Test/Python/test/datalabs/build/ -W ignore::DeprecationWarning
        - step:
            name: Lint
            script:
            - export VIRTUAL_ENV=/Build/Environment/Master
            - export PATH="$VIRTUAL_ENV/bin:$PATH"
            - ./Script/run.py pylint --extension-pkg-whitelist=pyodbc,numpy ${CWD}/Source/Python/* ${CWD}/Test/Python/*
