#!/bin/bash

# Set up variables
CWD=$(realpath .)
VIRTUAL_ENV=${CWD}/Environment/Master
RUN="python3 ${CWD}/Script/run.py"
TEMPLATE_FILES="${CWD}/Build/Master/requirements_template.txt ${CWD}/Build/Master/Pipfile_template.txt ${CWD}/Build/Master/conda_requirements_template.txt"

# Function to set up the virtual environment
setup_virtualenv() {
    export PATH="${VIRTUAL_ENV}/bin:${PATH}"
}

# Function to run tests
run_tests() {
    setup_virtualenv
    ${RUN} ${VIRTUAL_ENV}/bin/pytest -vv Test/Python/ Test/Python/test/datalabs/build/ -W ignore::DeprecationWarning
}

# Function to set up test files
setup_test_files() {
    cp ${TEMPLATE_FILES} ${CWD}/Test/Python/test/datalabs/environment/
}

# Main function
main() {
    setup_test_files
    run_tests
}

# Run the main function
main
