#!/bin/bash

REPO_DIR=/Users/plane/Development/hs-datalabs
RUN=${REPO_DIR}/Script/run.py
export VIRTUAL_ENV=${REPO_DIR}/Environment/Master
export PATH="$VIRTUAL_ENV/bin:$PATH"


main() {
    check_dag_runs_by_environment dev $(date "+%Y-%m-%d 00:00:00")

    check_dag_runs_by_environment tst $(date "+%Y-%m-%d 01:00:00")

    check_dag_runs_by_environment prd $(date "+%Y-%m-%d 10:00:00")
}


check_dag_runs_by_environment() {
    environment=$1
    execution_time=$2

    $(apigw_assume_role.sh $environment | grep source)
    dag_status=$(${RUN} get-dag-runs -d ONEVIEW -e $environment -n 1)

    environment_upper=$(echo "$environment" | tr '[:upper:]' '[:lower:]')

    if [[ "$dag_status" == "$execution_time"* ]]; then
        echo "OneView DAG was started on ${environment_upper}"
    else
        echo "OneView DAG did not start on ${environment_upper}"
    fi

    if [[ "$dag_status" == *"Finished" ]]; then
        echo "OneView DAG finished on ${environment_upper}"
    else
        echo "OneView DAG did not finish on ${environment_upper}:"
        echo $dag_status
    fi
}


main
