apiVersion: v1
kind: ConfigMap
metadata:
    name: oneview-type-of-practice
    namespace: hsg-data-labs-dev
data:
    # TypeOfPractice Extractor
    ONEVIEW__TYPE_OF_PRACTICE_EXTRACTOR__TASK_CLASS: 'datalabs.etl.jdbc.extract.JDBCExtractorTask'
    ONEVIEW__TYPE_OF_PRACTICE_EXTRACTOR__DATABASE_NAME: 'aims_prod:prd1srvxnet'
    ONEVIEW__TYPE_OF_PRACTICE_EXTRACTOR__DATABASE_PORT: '22093'
    ONEVIEW__TYPE_OF_PRACTICE_EXTRACTOR__SQL: "SELECT DISTINCT T.top_cd, T.description FROM informix.top_pr T;"
    ONEVIEW__TYPE_OF_PRACTICE_EXTRACTOR__DRIVER: 'com.informix.jdbc.IfxDriver'
    ONEVIEW__TYPE_OF_PRACTICE_EXTRACTOR__DRIVERTYPE: 'informix-sqli'
    ONEVIEW__TYPE_OF_PRACTICE_EXTRACTOR__JARPATH: './jdbc-4.50.2.fix-1.jar,./bson-3.8.0.jar'

    # TypeOfPractice Transformer
    ONEVIEW__TYPE_OF_PRACTICE_TRANSFORMER__TASK_CLASS: 'datalabs.etl.oneview.reference.transform.TypeOfPracticeTransformerTask'

    # TypeOfPractice Loader
    ONEVIEW__TYPE_OF_PRACTICE_LOADER__TASK_CLASS: 'datalabs.etl.s3.load.S3UnicodeTextFileLoaderTask'
    ONEVIEW__TYPE_OF_PRACTICE_LOADER__BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'
    ONEVIEW__TYPE_OF_PRACTICE_LOADER__BASEPATH: 'AMA/OneView'
    ONEVIEW__TYPE_OF_PRACTICE_LOADER__ENDPOINTURL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    ONEVIEW__TYPE_OF_PRACTICE_LOADER__FILES: 'type_of_practice.csv'

    # SpecialtyMerge Extractor
    ONEVIEW__SPECIALTY_MERGE_EXTRACTOR__TASK_CLASS: 'datalabs.etl.s3.extract.S3UnicodeTextFileExtractorTask'
    ONEVIEW__SPECIALTY_MERGE_EXTRACTOR__BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'
    ONEVIEW__SPECIALTY_MERGE_EXTRACTOR__BASEPATH: 'AMA/OneView'
    ONEVIEW__SPECIALTY_MERGE_EXTRACTOR__ENDPOINTURL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    ONEVIEW__SPECIALTY_MERGE_EXTRACTOR__FILES: 'specialty.csv,ppd_physician.csv'

    # SpecialtyMerge Transformer
    ONEVIEW__SPECIALTY_MERGE_TRANSFORMER__TASK_CLASS: 'datalabs.etl.oneview.reference.transform.TypeOfPracticeTransformerTask'

    # SpecialtyMerge Loader
    ONEVIEW__SPECIALTY_MERGE_LOADER__TASK_CLASS: 'datalabs.etl.s3.load.S3UnicodeTextFileLoaderTask'
    ONEVIEW__SPECIALTY_MERGE_LOADER__BUCKET: 'ama-hsg-datalabs-datalake-processing-onprem'
    ONEVIEW__SPECIALTY_MERGE_LOADER__BASEPATH: 'AMA/OneView'
    ONEVIEW__SPECIALTY_MERGE_LOADER__ENDPOINTURL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    ONEVIEW__SPECIALTY_MERGE_LOADER__FILES: 'specialty.csv'

    # Specialty Extractor
    ONEVIEW__SPECIALTY_EXTRACTOR__TASK_CLASS: 'datalabs.etl.jdbc.extract.JDBCExtractorTask'
    ONEVIEW__SPECIALTY_EXTRACTOR__DATABASE_NAME: 'aims_prod:prd1srvxnet'
    ONEVIEW__SPECIALTY_EXTRACTOR__DATABASE_PORT: '22093'
    ONEVIEW__SPECIALTY_EXTRACTOR__SQL: "SELECT DISTINCT S.spec_cd, S.description FROM informix.spec_pr S;"
    ONEVIEW__SPECIALTY_EXTRACTOR__DRIVER: 'com.informix.jdbc.IfxDriver'
    ONEVIEW__SPECIALTY_EXTRACTOR__DRIVERTYPE: 'informix-sqli'
    ONEVIEW__SPECIALTY_EXTRACTOR__JARPATH: './jdbc-4.50.2.fix-1.jar,./bson-3.8.0.jar'

    # Specialty Transformer
    ONEVIEW__SPECIALTY_TRANSFORMER__TASK_CLASS: 'datalabs.etl.oneview.reference.transform.SpecialtyTransformerTask'

    # Specialty Loader
    ONEVIEW__SPECIALTY_LOADER__TASK_CLASS: 'datalabs.etl.s3.load.S3UnicodeTextFileLoaderTask'
    ONEVIEW__SPECIALTY_LOADER__BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'
    ONEVIEW__SPECIALTY_LOADER__BASEPATH: 'AMA/OneView'
    ONEVIEW__SPECIALTY_LOADER__ENDPOINTURL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    ONEVIEW__SPECIALTY_LOADER__FILES: 'specialty.csv'
