apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  generation: 1
  labels:
    app: OneViewShell
  name: oneview-shell
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: OneViewShell
    deploymentconfig: oneview-shell
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: OneViewShell
        deploymentconfig: oneview-shell
    spec:
      containers:
      - command:
        - /bin/bash
        args:
        - -c
        - "sleep 86400"
        image: >-
          docker-registry.default.svc:5000/hsg-data-labs-dev/oneview-etl:1.2.1
        imagePullPolicy: IfNotPresent
        name: bitbucket-sync
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - bitbucket-sync
      from:
        kind: ImageStreamTag
        name: oneview-etl:1.2.2
        namespace: hsg-data-labs-dev
