#!/bin/bash

set -ex

PROJECT="${PROJECT:-OneView}"
ENVIRONMENT="${ENVIRONMENT:-sbx}"

CODE_BUCKET="ama-${ENVIRONMENT}-datalake-lambda-us-east-1"
FUNCTIONS=(
    "${PROJECT}-${ENVIRONMENT}-ETL"
    "${PROJECT}-${ENVIRONMENT}-API"
)
BUNDLES=(
    "${PROJECT}/ETL.zip"
    "${PROJECT}/API.zip"
)

for index in "${!FUNCTIONS[@]}"; do
  aws --no-paginate lambda update-function-code --function-name ${FUNCTIONS[index]} --s3-bucket ${CODE_BUCKET} --s3-key ${BUNDLES[index]} || exit $?
done
