#!/bin/bash

set -ex

PROJECT="${PROJECT:-OneView}"
ENVIRONMENT="${ENVIRONMENT:-sbx}"
CODE_BUCKET="${CODE_BUCKET:-ama-hsg-datalabs-lambda-code-sandbox}"
BUNDLE="${BUNDLE:-OneView}"

# FUNCTIONS="${PROJECT}Authorizer
#            ${PROJECT}-Endpoint
#            ${PROJECT}Convert
#            ${PROJECT}BundlePDF
#            ${PROJECT}Load
#            ${PROJECT}IngestionRouter
#            ${PROJECT}ProcessingRouter"
FUNCTIONS=""

for FUNCTION in ${FUNCTIONS}; do
  aws lambda update-function-code --function-name $FUNCTION --s3-bucket ${CODE_BUCKET} --s3-key ${BUNDLE}.zip || exit $?
  # aws --no-verify-ssl lambda update-function-code --function-name $FUNCTION --s3-bucket ${CODE_BUCKET} --s3-key ${BUNDLE}.zip || exit $?
done
