#!/bin/bash

ETCD_HOST=${ETCD_HOST:-}
ETCD_USERNAME=oneview
ETCD_PASSWORD=${ETCD_PASSWORD:-}

export

if [[ $ETCD_HOST != "" && $ETCD_PASSWORD != "" ]]; then
    eval $(Script/extract-etcd \
        --host ${ETCD_HOST} \
        --username ${ETCD_USERNAME} \
        --password "${ETCD_PASSWORD}" \
        --prefix=ONEVIEW_DATABASE_)

    DATABASE_HOST=$ONEVIEW_DATABASE_HOST
    DATABASE_PORT=$ONEVIEW_DATABASE_PORT
    DATABASE_NAME=$ONEVIEW_DATABASE_NAME
    DATABASE_USERNAME=$ONEVIEW_DATABASE_USERNAME
    DATABASE_PASSWORD=$ONEVIEW_DATABASE_PASSWORD
fi

${PWD}/Script/migrate-database upgrade OneView \
    --host ${DATABASE_HOST} \
    --port ${DATABASE_PORT} \
    --name ${DATABASE_NAME} \
    --username ${DATABASE_USERNAME} \
    --password ${DATABASE_PASSWORD}
