#!/bin/bash

set -ex

PROJECT=$1

export VIRTUAL_ENV=${PWD}/Environment/${PROJECT}
export PATH="$VIRTUAL_ENV/bin:$PATH"

export PYTHONPATH=${PWD}/Source/Python
python -c 'from datalabs.deploy.database import create_unless_exists; create_unless_exists()'
