#!/usr/bin/env bash

set -eux

SCRIPT_PATH=`realpath $0`
SCRIPT_BASE_PATH=`dirname $SCRIPT_PATH`
RUN="${SCRIPT_BASE_PATH}/run.py python"

AWS_DEFAULT_REGION=us-east-1
declare -A ENVIRONMENTS=(
    [master]=sbx
    [dev]=dev
    [test]=tst
    [stage]=itg
    [prod]=prd
)

BRANCH=
ENVIRONMENT=
PROJECT=
VERSION=


main() {
    process_arguments "$@"

    create_server_config

    build_package

    upload_package
}


process_arguments() {
    while (( "$#" )); do
      case "$1" in
        -h|--help)
            print_usage
            exit 0
            ;;
        -b|--branch)
            BRANCH=$2
            shift
            shift
            ;;
        -e|--environment)
            ENVIRONMENT=$2
            shift
            shift
            ;;
        -p|--project)
            PROJECT=$2
            shift
            shift
            ;;
        -v|--version)
            VERSION=$2
            shift
            shift
            ;;
        *)
            echo "Unexpected argument $1"
            print_usage
            exit 0
            ;;
      esac
    done

    if [[ "$VERSION" != "" ]]; then
        ENVIRONMENT=sbx
    elif [[ "$BRANCH" != "" ]]; then
        ENVIRONMENT=${ENVIRONMENTS[$BRANCH]}
    elif [[ "$ENVIRONMENT" == "" ]]; then
        echo "Missing environment argument."
        exit 1
    elif  [[ "$PROJECT" == "" ]]; then
        echo "Missing project argument."
        exit 1
    fi
}


build_package() {
    source Build/${PROJECT}/.ci/release.sh ${ENVIRONMENT}

    package=${RELEASE_NAME#datalabs-}

    if [[ "$VERSION" != "" ]]; then
        RELEASE_VERSION=$VERSION
    else
        VERSION=$RELEASE_VERSION
    fi

    if [[ "$RELEASE_VERSION" == "dev" ]]; then
        generate_dev_version
    fi
    echo "Version: $VERSION"

    Script/bundle-java-project --in-place --directory Release/ --version $VERSION --package $package $PROJECT
}


upload_package() {
    cd Release

    mvn deploy
}


print_usage() {
    echo "Usage: deploy-java-package [OPTIONS]..."
    echo "Build and upload a Python package for a component."
    echo
    echo "OPTIONS"
    echo "  -h, --help                            print this usage text"
    echo "  -e, --environment                     deployment environment (dev, tst, itg, prd)"
    echo "  -p, --project                         project path relative to Build/"
}


generate_dev_version() {
    current_version=$(
        aws --profile default codeartifact list-package-versions \
            --domain datalabs --repository cpt-link-sbx --namespace org.ama-assn.datalabs --package dtk-core \
            --format maven --sort-by PUBLISHED_TIME \
            | grep -m 1 -e '"version": ' | sed 's/..*: "//' | sed 's/",//'
    )

    if [[ "$current_version" == "" ]]; then
        current_version="0.1.0"
    fi

    base_version=$(echo $current_version | sed 's/\.dev.*//')
    dev_version=$(echo $current_version | sed 's/..*dev//')

    if [[ "$dev_version" == "$current_version" ]]; then
        VERSION="${current_version}.dev0"
    else
        VERSION="${base_version}.dev$(expr $dev_version + 1)"
    fi
}

create_server_config() {
    if [ -e ~/.m2/settings.xml ]; then
        echo "The file ~/.m2/settings.xml already exists. Aborting..."

        exit 1
    fi
    export CODEARTIFACT_AUTH_TOKEN=$(
        aws --profile default codeartifact get-authorization-token --domain datalabs\
        --query authorizationToken --output text
    )

    cat > ~/.m2/settings.xml <<EOF
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
    <servers>
        <server>
            <id>codeartifact</id>
            <username>aws</username>
            <password>\${env.CODEARTIFACT_AUTH_TOKEN}</password>
        </server>
    </servers>
</settings>
EOF
}


main "$@"
