#!/usr/bin/env bash

set -eux

SCRIPT_PATH=`realpath $0`
SCRIPT_BASE_PATH=`dirname $SCRIPT_PATH`
. ${SCRIPT_BASE_PATH}/determine_package_version.sh
RUN="${SCRIPT_BASE_PATH}/run.py python"

AWS_DEFAULT_REGION=us-east-1

REPOSITORY=
ENVIRONMENT=
PROJECT=
PACKAGE=
VERSION=
DEPLOYED_VERSION=


main() {
    process_arguments "$@"

    get_deployed_version

    determine_package_info

    if [[ "$RELEASE_VERSION" == "dev" || "$DEPLOYED_VERSION" != "$RELEASE_VERSION" ]]; then
        build_container_image

        upload_container_image
    fi
}


process_arguments() {
    while (( "$#" )); do
      case "$1" in
        -h|--help)
            print_usage
            exit 0
            ;;
        -e|--environment)
            ENVIRONMENT=$2
            shift
            shift
            ;;
        -p|--project)
            PROJECT=$2
            shift
            shift
            ;;
        -R|--repo)
            REPOSITORY=$2
            shift
            shift
            ;;
        *)
            echo "Unexpected argument $1"
            print_usage
            exit 1
            ;;
      esac
    done
}


get_deployed_version() {
    printenv | grep AWS
    deployed_versions=(
        $(
            aws ecr list-images --repository-name ${REPOSITORY} | jq '.imageIds[].imageTag' | grep -v null | sed 's/"//g'\
            | grep -v latest | xargs -n1 | sort | xargs
        )
    )

    version_count=${#deployed_versions[@]}
    if [[ $version_count > 0 ]]; then
        set +e
        index=$(expr $version_count - 1)
        set -e
        DEPLOYED_VERSION=${deployed_versions[$index]}
    fi
}

build_container_image() {
    docker build \
        --build-arg ENVIRONMENT=${ENVIRONMENT} \
        --build-arg PROJECT=${PROJECT} \
        --build-arg AWS_ACCESS_KEY_ID_SANDBOX=${AWS_ACCESS_KEY_ID_SANDBOX} \
        --build-arg AWS_SECRET_ACCESS_KEY_SANDBOX=${AWS_SECRET_ACCESS_KEY_SANDBOX} \
        --build-arg MAVEN_VERSION=$(curl --silent https://apache.osuosl.org/maven/maven-3/ | grep 3.9 | sed 's/^..*href="\([^/][^/]*\)..*/\1/g' | tail -n 1) \
        -t ${PACKAGE} -f ./Build/${PROJECT}/Dockerfile ./
}

upload_container_image() {
    ECR_ACCOUNT=394406051370

    if [[ $ENVIRONMENT == "sbx" ]]; then
        ECR_ACCOUNT=644454719059
    fi

    aws ecr get-login-password --region us-east-1 \
        | docker login --username AWS --password-stdin ${ECR_ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com

    docker tag  ${PACKAGE} ${ECR_ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/${REPOSITORY}:${VERSION}
    docker push ${ECR_ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/${REPOSITORY}:${VERSION}

    docker tag ${PACKAGE} ${ECR_ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/${REPOSITORY}:latest
    docker push ${ECR_ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/${REPOSITORY}:latest
}


print_usage() {
    echo "Usage: deploy-lambda-function [OPTIONS]..."
    echo "Bundle and upload a code bundle for a Lambda function."
    echo
    echo "OPTIONS"
    echo "  -h, --help                            print this usage text"
    echo "  -e, --environment <environment>       deployment environment (dev, tst, itg, prd)"
    echo "  -p, --project <project>               project path relative to Build/"
    echo "  -R, --repo <bundle>                   ECR repository name"
}


main "$@"
