#!/bin/bash

set -ex

PROJECT="${PROJECT:-CPT}"

./Script/setup-virtual-environment Master/BitBucketPipelines
export VIRTUAL_ENV=${PWD}/Environment/Master/BitBucketPipelines
export PATH="$VIRTUAL_ENV/bin:$PATH"

cat Build/Master/requirements.txt | grep pip== > pip-requirements.txt
pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r pip-requirements.txt

pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --target Bundle/ -r Build/${PROJECT}/requirements.txt

export PYTHONPATH=${PWD}/Source/Python
python -c 'from datalabs.deploy.cpt.database import create_unless_exists; create_unless_exists()'
