#!/bin/bash

set -ex

PROJECT="${PROJECT:-CPT}"
ENVIRONMENT="${ENVIRONMENT:-sbx}"
CODE_BUCKET="${CODE_BUCKET:-ama-${ENVIRONMENT}-datalake-lambda-us-east-1}"
BUNDLE="${BUNDLE:-ETL}"

FUNCTIONS="${PROJECT}-API-${ENVIRONMENT}-Authorizer
           ${PROJECT}-API-${ENVIRONMENT}-Endpoint
           ${PROJECT}-API-${ENVIRONMENT}-Convert
           ${PROJECT}-API-${ENVIRONMENT}-BundlePDF
           ${PROJECT}-API-${ENVIRONMENT}-Load
           ${PROJECT}-API-${ENVIRONMENT}-IngestionRouter
           ${PROJECT}-API-${ENVIRONMENT}-ProcessingRouter"

for FUNCTION in ${FUNCTIONS}; do
  aws lambda update-function-code --function-name $FUNCTION --s3-bucket ${CODE_BUCKET} --s3-key CPT/${BUNDLE}.zip || exit $?
  # aws --no-verify-ssl lambda update-function-code --function-name $FUNCTION --s3-bucket ${CODE_BUCKET} --s3-key ${BUNDLE}.zip || exit $?
done
