#!/bin/bash

set -ex

ls ${PWD}/Bundle.zip
aws s3 cp ${PWD}/Bundle.zip s3://ama-hsg-datalabs-lambda-code-sandbox/${PROJECT}/${PROJECT}.zip
aws s3 ls s3://ama-hsg-datalabs-lambda-code-sandbox/${PROJECT}/${PROJECT}.zip
