NPI_COLUMNS = {
    "NPI_DATA_ID": "npiDataId",
    "ENTITY_ID": "entityId",
    "NPI_CD": "npiCd",
    "ENUMERATION_DT": "enumerationDate",
    "DEACTIVATION_DT": "deactivationDate",
    "REACTIVATION_DT": "reactivationDate",
    "REP_NPI_CD": "repNpiCode",
    "RPTD_DT": "rptdDate",
    "INSERT_DTM": "insertDtm",
    "INSERT_USER_ID": "insertUserId",
    "END_DT": "endDate",
    "FIRST_NAME": "firstName",
    "MIDDLE_NAME": "middleName",
    "LAST_NAME": "lastName",
}
