apiVersion: batch/v1
kind: Job
metadata:
  name: ppd-oneview-etl
spec:
  template:
    spec:
      containers:
      - name: ppd-oneview-etl
        image: >-
          docker-registry.default.svc:5000/hsg-data-labs-dev/ppd-oneview-etl:latest
        imagePullPolicy: Always
        command:
        - /OneView/entrypoint.sh
        args:
        - /bin/bash
        - -c
        - --
        - "while true; do sleep 30; done;"
        # - python
        # - -c
        # - "'import awslambda; print(awslambda.handler(None, None))'"
        env:
        - name: EXTRACTOR__DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: hsg-data-labs-ods
              key: username
        - name: EXTRACTOR__DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hsg-data-labs-ods
              key: password
        - name: LOADER__DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: hsg-data-labs-postgres
              key: username
        - name: LOADER__DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hsg-data-labs-postgres
              key: password
        envFrom:
        - configMapRef:
            name: ppd-oneview-etl
      restartPolicy: Never
