apiVersion: batch/v1
kind: Job
metadata:
  name: ppd-oneview-etl
spec:
  template:
    spec:
      template:
        spec:
          containers:
          - name: ppd-oneview-etl
            image: >-
              docker-registry.default.svc:5000/hsg-data-labs-dev/ppd-oneview-etl
            imagePullPolicy: Always
            command:
            - /OneView/entrypoint.sh
            args:
            # - /bin/bash
            # - -c
            # - --
            # - "while true; do sleep 30; done;"
            - python
            - -c
            - "import awslambda; import os; os.environ['TASK_WRAPPER_CLASS'] = 'datalabs.etl.awslambda.ETLTaskWrapper'; os.environ['TASK_CLASS'] = 'datalabs.etl.task.ETLTask'; print(awslambda.handler(None, None)) /bin/bash"
            env:
            - name: EXTRACTOR_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hsg-data-labs-ods
                  key: username
            - name: EXTRACTOR_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hsg-data-labs-ods
                  key: password
            - name: LOADER_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hsg-data-labs-postgres
                  key: username
            - name: LOADER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hsg-data-labs-postgres
                  key: password
            envFrom:
            - configMapRef:
                name: oneview-etl
          restartPolicy: Never
