#!/bin/bash

set -ex

PROJECT="${PROJECT:-CPT}"
ENVIRONMENT="${ENVIRONMENT:-dev}"
CODE_BUCKET="${CODE_BUCKET:-ama-${ENVIRONMENT}-datalake-lambda-us-east-1}"

FUNCTIONS="${PROJECT}-API-${ENVIRONMENT}-Authorizer
           ${PROJECT}-API-${ENVIRONMENT}-Endpoint
           ${PROJECT}-API-${ENVIRONMENT}-ETL
           ${PROJECT}-API-${ENVIRONMENT}-BulkAuthorizer
           ${PROJECT}-API-${ENVIRONMENT}-BulkEndpoint"

for FUNCTION in ${FUNCTIONS}; do
  aws lambda update-function-code --function-name $FUNCTION --s3-bucket ${CODE_BUCKET} --s3-key ${PROJECT}/ETL.zip || exit $?
  # aws --no-verify-ssl lambda update-function-code --function-name $FUNCTION --s3-bucket ${CODE_BUCKET} --s3-key ${BUNDLE}.zip || exit $?
done
