""" OneView ETL DAG definition. """
from   datalabs.etl.dag import DAG
from   datalabs.etl.http.extract import HTTPFileExtractorTask
from   datalabs.etl.jdbc.extract import JDBCExtractorTask
import datalabs.etl.oneview.credentialing.transform as credentialing
from   datalabs.etl.oneview.iqvia.transform import IQVIABusinessTransformerTask, IQVIAProviderTransformerTask
import datalabs.etl.oneview.link.transform as link
from   datalabs.etl.oneview.melissa.transform import MelissaTransformerTask
from   datalabs.etl.oneview.ppd.transform import PPDTransformerTask
from   datalabs.etl.oneview.race_ethnicity.transform import RaceEthnicityTransformerTask
import datalabs.etl.oneview.reference.transform as reference
import datalabs.etl.oneview.residency.transform as residency
from   datalabs.etl.orm.load import ORMLoaderTask
from   datalabs.etl.sftp.extract import SFTPFileExtractorTask


class OneViewDAG(DAG):
    EXTRACT_PPD: JDBCExtractorTask
    EXTRACT_TYPE_OF_PRACTICE: JDBCExtractorTask
    EXTRACT_PRESENT_EMPLOYMENT: JDBCExtractorTask
    EXTRACT_MAJOR_PROFESSIONAL_ACTIVITY: JDBCExtractorTask
    EXTRACT_CORE_BASED_STATISTICAL_AREA: HTTPFileExtractorTask
    EXTRACT_FEDERAL_INFORMATION_PROCESSING_STANDARD_COUNTY: HTTPFileExtractorTask
    EXTRACT_SPECIALTY: JDBCExtractorTask
    EXTRACT_RESIDENCY: SFTPFileExtractorTask
    EXTRACT_IQVIA: JDBCExtractorTask
    EXTRACT_CREDENTIALING_MAIN: JDBCExtractorTask
    EXTRACT_CREDENTIALING_ADDRESSES: SFTPFileExtractorTask
    EXTRACT_PHYSICIAN_RACE_ETHNICITY: SFTPFileExtractorTask
    EXTRACT_MELISSA: JDBCExtractorTask
    EXTRACT_PHYSICIAN_NATIONAL_PROVIDER_IDENTIFIERS: JDBCExtractorTask
    CREATE_PHYSICIAN_TABLE: PPDTransformerTask
    CREATE_TYPE_OF_PRACTICE_TABLE: reference.TypeOfPracticeTransformerTask
    CREATE_PRESENT_EMPLOYMENT_TABLE: reference.PresentEmploymentTransformerTask
    CREATE_MAJOR_PROFESSIONAL_ACTIVITY_TABLE: reference.MajorProfessionalActivityTransformerTask
    CREATE_FEDERAL_INFORMATION_PROCESSING_STANDARD_COUNTY_TABLE:\
        reference.FederalInformationProcessingStandardCountyTransformerTask
    CREATE_CORE_BASED_STATISTICAL_AREA_TABLE: reference.CoreBasedStatisticalAreaTransformerTask
    REMOVE_UNUSED_SPECIALTIES: reference.SpecialtyMergeTransformerTask
    CREATE_RESIDENCY_PROGRAM_TABLES: residency.ResidencyTransformerTask
    CREATE_BUSINESS_TABLE: IQVIABusinessTransformerTask
    CREATE_PROVIDER_TABLE: IQVIAProviderTransformerTask
    CREATE_CREDENTIALING_CUSTOMER_PRODUCT_AND_ORDER_TABLES: credentialing.CredentialingTransformerTask
    MERGE_CREDENTIALING_ADDRESSES_INTO_CUSTOMER_TABLE: credentialing.CredentialingFinalTransformerTask
    CREATE_PHYSICIAN_RACE_ETHNICITY_TABLE: RaceEthnicityTransformerTask
    CREATE_MELISSA_TABLES: MelissaTransformerTask
    CREATE_CREDENTIALING_CUSTOMER_INSTITUTION_TABLE: link.CredentialingCustomerInstitutionTransformerTask
    CREATE_CREDENTIALING_CUSTOMER_BUSINESS_TABLE: link.CredentialingCustomerBusinessTransformerTask
    CREATE_RESIDENCY_PROGRAM_PHYSICIAN_TABLE: link.ResidencyProgramPhysicianTransformerTask
    LOAD_PHYSICIAN_TABLE_INTO_DATABASE: ORMLoaderTask
    LOAD_REFERENCE_TABLES_INTO_DATABASE: ORMLoaderTask
    LOAD_RESIDENCY_TABLES_INTO_DATABASE: ORMLoaderTask
    LOAD_IQVIA_TABLES_INTO_DATABASE: ORMLoaderTask
    LOAD_RACE_ETHNICITY_TABLE_INTO_DATABASE: ORMLoaderTask
    LOAD_CREDENTIALING_TABLES_INTO_DATABASE: ORMLoaderTask
    LOAD_MELISSA_TABLES_INTO_DATABASE: ORMLoaderTask
    LOAD_LINKING_TABLES_INTO_DATABASE: ORMLoaderTask


# pylint: disable=pointless-statement
OneViewDAG.EXTRACT_PPD >> OneViewDAG.CREATE_PHYSICIAN_TABLE
OneViewDAG.EXTRACT_PHYSICIAN_NATIONAL_PROVIDER_IDENTIFIERS >> OneViewDAG.CREATE_PHYSICIAN_TABLE
OneViewDAG.CREATE_PHYSICIAN_TABLE >> OneViewDAG.LOAD_PHYSICIAN_TABLE_INTO_DATABASE
OneViewDAG.EXTRACT_TYPE_OF_PRACTICE >> OneViewDAG.CREATE_TYPE_OF_PRACTICE_TABLE \
    >> OneViewDAG.LOAD_REFERENCE_TABLES_INTO_DATABASE
OneViewDAG.EXTRACT_PRESENT_EMPLOYMENT >> OneViewDAG.CREATE_PRESENT_EMPLOYMENT_TABLE \
    >> OneViewDAG.LOAD_REFERENCE_TABLES_INTO_DATABASE
OneViewDAG.EXTRACT_MAJOR_PROFESSIONAL_ACTIVITY >> OneViewDAG.CREATE_MAJOR_PROFESSIONAL_ACTIVITY_TABLE \
    >> OneViewDAG.LOAD_REFERENCE_TABLES_INTO_DATABASE
OneViewDAG.EXTRACT_FEDERAL_INFORMATION_PROCESSING_STANDARD_COUNTY \
    >> OneViewDAG.CREATE_FEDERAL_INFORMATION_PROCESSING_STANDARD_COUNTY_TABLE
OneViewDAG.CREATE_FEDERAL_INFORMATION_PROCESSING_STANDARD_COUNTY_TABLE >> OneViewDAG.LOAD_REFERENCE_TABLES_INTO_DATABASE
OneViewDAG.EXTRACT_CORE_BASED_STATISTICAL_AREA >> OneViewDAG.CREATE_CORE_BASED_STATISTICAL_AREA_TABLE \
    >> OneViewDAG.LOAD_REFERENCE_TABLES_INTO_DATABASE
OneViewDAG.EXTRACT_SPECIALTY >> OneViewDAG.REMOVE_UNUSED_SPECIALTIES
OneViewDAG.CREATE_PHYSICIAN_TABLE >> OneViewDAG.REMOVE_UNUSED_SPECIALTIES
OneViewDAG.REMOVE_UNUSED_SPECIALTIES >> OneViewDAG.LOAD_REFERENCE_TABLES_INTO_DATABASE
OneViewDAG.EXTRACT_RESIDENCY >> OneViewDAG.CREATE_RESIDENCY_PROGRAM_TABLES \
    >> OneViewDAG.LOAD_RESIDENCY_TABLES_INTO_DATABASE
OneViewDAG.EXTRACT_IQVIA >> OneViewDAG.CREATE_BUSINESS_AND_PROVIDER_TABLES >> OneViewDAG.LOAD_IQVIA_TABLES_INTO_DATABASE
OneViewDAG.EXTRACT_CREDENTIALING_MAIN >> OneViewDAG.CREATE_CREDENTIALING_CUSTOMER_PRODUCT_AND_ORDER_TABLES
OneViewDAG.EXTRACT_CREDENTIALING_ADDRESSES >> OneViewDAG.MERGE_CREDENTIALING_ADDRESSES_INTO_CUSTOMER_TABLE
OneViewDAG.CREATE_CREDENTIALING_CUSTOMER_PRODUCT_AND_ORDER_TABLES \
    >> OneViewDAG.MERGE_CREDENTIALING_ADDRESSES_INTO_CUSTOMER_TABLE
OneViewDAG.MERGE_CREDENTIALING_ADDRESSES_INTO_CUSTOMER_TABLE >> OneViewDAG.LOAD_CREDENTIALING_TABLES_INTO_DATABASE
OneViewDAG.EXTRACT_PHYSICIAN_RACE_ETHNICITY >> OneViewDAG.CREATE_PHYSICIAN_RACE_ETHNICITY_TABLE \
    >> OneViewDAG.LOAD_RACE_ETHNICITY_TABLE_INTO_DATABASE
OneViewDAG.MERGE_CREDENTIALING_ADDRESSES_INTO_CUSTOMER_TABLE \
    >> OneViewDAG.CREATE_CREDENTIALING_CUSTOMER_INSTITUTION_TABLE
OneViewDAG.CREATE_RESIDENCY_PROGRAM_TABLES >> OneViewDAG.CREATE_CREDENTIALING_CUSTOMER_INSTITUTION_TABLE
OneViewDAG.CREATE_CREDENTIALING_CUSTOMER_INSTITUTION_TABLE >> OneViewDAG.LOAD_LINKING_TABLES_INTO_DATABASE
OneViewDAG.MERGE_CREDENTIALING_ADDRESSES_INTO_CUSTOMER_TABLE >> OneViewDAG.CREATE_CREDENTIALING_CUSTOMER_BUSINESS_TABLE
OneViewDAG.CREATE_BUSINESS_AND_PROVIDER_TABLES >> OneViewDAG.CREATE_CREDENTIALING_CUSTOMER_BUSINESS_TABLE
OneViewDAG.CREATE_CREDENTIALING_CUSTOMER_BUSINESS_TABLE >> OneViewDAG.LOAD_LINKING_TABLES_INTO_DATABASE
OneViewDAG.CREATE_RESIDENCY_PROGRAM_TABLES >> OneViewDAG.CREATE_RESIDENCY_PROGRAM_PHYSICIAN_TABLE
OneViewDAG.CREATE_PHYSICIAN_TABLE >> OneViewDAG.CREATE_RESIDENCY_PROGRAM_PHYSICIAN_TABLE
OneViewDAG.CREATE_RESIDENCY_PROGRAM_PHYSICIAN_TABLE >> OneViewDAG.LOAD_LINKING_TABLES_INTO_DATABASE
OneViewDAG.EXTRACT_MELISSA >> OneViewDAG.CREATE_MELISSA_TABLES >> OneViewDAG.LOAD_MELISSA_TABLES_INTO_DATABASE
