apiVersion: v1
kind: ConfigMap
metadata:
    name: contact-id-etl
    namespace: hsg-data-labs-dev
data:
    # TASK_WRAPPER_CLASS: datalabs.etl.dag.task.DAGTaskWrapper

    # Contact ID Extractor-
    CONTACT_ID__EXTRACT_ADVANTAGE__DATABASE_NAME: 'AdvDbDEV;domain=AMA_NT'
    CONTACT_ID__EXTRACT_ADVANTAGE__DATABASE_USERNAME: ${DATABASE_USERNAME}
    CONTACT_ID__EXTRACT_ADVANTAGE__DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    CONTACT_ID__EXTRACT_ADVANTAGE__DATABASE_HOST: '10.195.194.135'
    CONTACT_ID__EXTRACT_ADVANTAGE__DATABASE_PORT: '1433'

    CONTACT_ID__EXTRACT_ADVANTAGE__SQL: >-
        select
            CUS.[Isell Login],
            OH.[Customer Number],
            ADR.[Company Name],
            CUS.[Customer Category],
            OD.[Item Number],
            YEAR(OH.[ORDER DATE]) as Year,
            month(oh.[ORDER DATE]) as Month,
            Sum(OD.[Quantity]) as Num_Profs,
            Sum(OD.[Item Net]) as Rev
        from uv_AMA_HSG_OrderHeader OH
        join uv_AMA_HSG_OrderDetails OD on OH.[Order Number] = OD.[Order Number]
        JOIN (
            SELECT DISTINCT
                [Customer Number],
                [Isell Login],
                [Record Status],
                [Date Added],
                [Update Date],
                [Updated By],
                [Purchase Order Required],
                [Credit Limit],
                [Current A/R Balance],
                [Salesman Code],
                [Customer Type],
                Promotable,
                [Invoice Terms],
                [Physician Count],
                [Customer Category],
                [API Vendor],
                [Default Address Code],
                [Billing Currency],
                [Price Code],
                [Discount Type],
                [Discount Percent],
                [Check for Duplicate PO]
            FROM uv_AMA_HSG_Customers
        ) CUS ON OH.[Customer Number] = CUS.[Customer Number]
        join uv_AMA_HSG_Addresses ADR on CUS.[Customer Number] = ADR.[Customer Number] and CUS.[Default Address Code] = ADR.[Address Code]
        where
            OH.[Customer Number] NOT IN ('000001887301', '000002076258', '000002793326', '000003014654', '000002099673', '000002506885', '000003014653', '000003014654')  -- AMA Service Monitor Account
            and OH.[Order Type] != 'C'
            and OH.[Order Date] between convert(datetime,'2018-01-01') and convert(datetime,'2021-03-31')
            and CUS.[Customer Type] in ('EPROFILE', 'INSTIT')
            and CUS.[Customer Category] <>''
            and CUS.[Customer Category] NOT IN ('BD','SMS', 'CMS', 'SPMS')
            and OD.[Price Code] NOT IN ('AMABOA', 'AMAHSB', 'MEMBER')
            and OD.[Promotion Code] NOT IN ('MEMDISC', 'CREDDISC')
            and OD.[Volume Price Code] NOT IN ('AMABOAF', 'AMABOAR', 'AMAHSBC', 'AMAHSBF', 'AMAHSBP', 'AMAHSBR', 'HARVEY')
            and OD.[Item Number] NOT IN ('FAPP+CM','RAPP+CM','SELFINQ', 'FCVO')
            and OD.[Item Number] NOT LIKE 'PVS%'
        group by
            CUS.[Isell Login],
            OH.[Customer Number],
            ADR.[Company Name],
            CUS.[Customer Category],
            YEAR(OH.[ORDER DATE]),
            month(oh.[ORDER DATE]),
            OD.[Item Number];
        select
          distinct( PART.[Participant Customer Number])
        from uv_AMA_HSG_Agreements AGR
        join uv_AMA_HSG_Agreement_Participants PART on AGR.[Agreement ID] = PART.[Agreement ID] and AGR.[TERM] = PART.[TERM] and AGR.[Version] = PART.[Version]
        where AGR.[Agreement Status] = 'A';
    CONTACT_ID__EXTRACT_ADVANTAGE__DRIVER: 'net.sourceforge.jtds.jdbc.Driver'
    CONTACT_ID__EXTRACT_ADVANTAGE__DRIVER_TYPE: 'jtds:sqlserver'
    CONTACT_ID__EXTRACT_ADVANTAGE__JAR_PATH: './jtds-1.3.1.jar'

    CONTACT_ID__EXTRACT_ADVANTAGE__CACHE_OUTPUT_CLASS: 'datalabs.etl.dag.cache.s3.S3TaskDataCache'
    CONTACT_ID__EXTRACT_ADVANTAGE__CACHE_OUTPUT_BASE_PATH: 'AMA/ContactID/%Y%m%d'
    CONTACT_ID__EXTRACT_ADVANTAGE__CACHE_OUTPUT_ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__EXTRACT_ADVANTAGE__CACHE_OUTPUT_ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__EXTRACT_ADVANTAGE__CACHE_OUTPUT_SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__EXTRACT_ADVANTAGE__CACHE_OUTPUT_BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'
    CONTACT_ID__EXTRACT_ADVANTAGE__CACHE_OUTPUT_FILES: 'API_Orders.csv, Active_Subscription.csv'
    CONTACT_ID__EXTRACT_ADVANTAGE__CACHE_OUTPUT_INCLUDE_DATESTAMP: 'false'


    CONTACT_ID__EXTRACT_VALID__BASE_PATH: '/Valid/From_Valid/'
    CONTACT_ID__EXTRACT_VALID__FILES: '%Y%m%d_*/SFMC_FlatFile_%Y%m%d.txt'
    CONTACT_ID__EXTRACT_VALID__HOST: 'eft.ama-assn.org'
    CONTACT_ID__EXTRACT_VALID__USERNAME: ${EFT_USERNAME}
    CONTACT_ID__EXTRACT_VALID__PASSWORD: ${EFT_PASSWORD}

    CONTACT_ID__EXTRACT_VALID__CACHE_OUTPUT_CLASS: 'datalabs.etl.dag.cache.s3.S3TaskDataCache'
    CONTACT_ID__EXTRACT_VALID__CACHE_OUTPUT_BASE_PATH: 'AMA/ContactID/%Y%m%d'
    CONTACT_ID__EXTRACT_VALID__CACHE_OUTPUT_ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__EXTRACT_VALID__CACHE_OUTPUT_ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__EXTRACT_VALID__CACHE_OUTPUT_SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__EXTRACT_VALID__CACHE_OUTPUT_BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'
    CONTACT_ID__EXTRACT_VALID__CACHE_OUTPUT_FILES: 'SFMC_FLATFILE_%Y%m%d.txt'
    CONTACT_ID__EXTRACT_VALID__CACHE_OUTPUT_INCLUDE_DATESTAMP: 'false'


    CONTACT_ID__EXTRACT_ORGMANAGER__DATABASE_NAME: 'DEVSSO'       #prod
    CONTACT_ID__EXTRACT_ORGMANAGER__DATABASE_USERNAME: ${DATABASE_USERNAME}
    CONTACT_ID__EXTRACT_ORGMANAGER__DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    CONTACT_ID__EXTRACT_ORGMANAGER__DATABASE_HOST: '10.195.180.69'
    CONTACT_ID__EXTRACT_ORGMANAGER__DATABASE_PORT: '50050'


    CONTACT_ID__EXTRACT_ORGMANAGER__SQL: >-
        select
            mq.FIRST_NM,
            mq.LAST_NM,
            mq.EMAIL,
            mq.ORG_NAME,
            mq.ORGANIZATION_TYPE,
            mq.ADVANTAGE_ID,
            mq.ADDRESS_LINE_1,
            mq.ADDRESS_LINE_2,
            mq.CITY,
            mq.STATE,
            mq.ZIPCODE,
            mq.PHONE_NUMBER,
            mq.ORG_ISELL_ID
        from
            (select
                ou.ORG_USER_ID,
                lq.FIRST_NM,
                lq.LAST_NM,
                lq.EMAIL,
                lq.ORG_NAME,
                lq.ORGANIZATION_TYPE,
                lq.ADVANTAGE_ID,
                lq.ADDRESS_LINE_1,
                lq.ADDRESS_LINE_2,
                lq.CITY,
                lq.STATE,
                lq.ZIPCODE,
                lq.PHONE_NUMBER,
                lq.ORG_ISELL_ID
        from
            (select
                usr.USER_ID,
                usr.FIRST_NM,
                usr.LAST_NM,
                usr.EMAIL,
                oou.ORG_NAME,
                oou.ORGANIZATION_TYPE,
                oou.ADVANTAGE_ID,
                oou.ADDRESS_LINE_1,
                oou.ADDRESS_LINE_2,
                oou.CITY,
                oou.STATE,
                oou.ZIPCODE,
                oou.PHONE_NUMBER,
                oou.ORG_ISELL_ID
        from
            sso.PC_USER usr
        inner join
            (select *
            from
                sso.ORG_USER ou
            inner join
                (select
                    o.ORG_ID as SEL_ORG_ID,
                    o.ORG_NAME,
                    o.ORGANIZATION_TYPE,
                    o.ADVANTAGE_ID,
                    o.ADDRESS_LINE_1,
                    o.ADDRESS_LINE_2,
                    o.CITY,
                    o.STATE,
                    o.ZIPCODE,
                    o.PHONE_NUMBER,
                    ois.ISELL_ID as ORG_ISELL_ID
            from sso.ORGANIZATION o
        left outer join sso.ORG_ISELL ois on o.ORG_ID=ois.ORG_ID
        where
            STATUS=1
            --and ois.isell_id = '01AM30613'
            AND ADVANTAGE_ID IS NOT NULL) org
        on ou.ORG_ID=org.SEL_ORG_ID) oou on usr.USER_ID=oou.USER_ID
            and not email like '%@ama-assn.org'
            and not email like '%@mailinator.com'and usr.USER_STATUS='ACTIVE')lq
        inner join sso.ORG_USER ou on lq.USER_ID=ou.USER_ID) mq
        inner join sso.ORG_USER_ROLE our on mq.ORG_USER_ID=our.ORG_USER_ID
        where our.ROLE_ID in ('1','2','3');


    CONTACT_ID__EXTRACT_ORGMANAGER__DRIVER: 'com.ibm.db2.jcc.DB2Jcc'
    CONTACT_ID__EXTRACT_ORGMANAGER__DRIVER_TYPE: 'db2'
    CONTACT_ID__EXTRACT_ORGMANAGER__JAR_PATH: './db2jcc4.jar'

    CONTACT_ID__EXTRACT_ORGMANAGER__CACHE_OUTPUT_CLASS: 'datalabs.etl.dag.cache.s3.S3TaskDataCache'
    CONTACT_ID__EXTRACT_ORGMANAGER__CACHE_OUTPUT_BASE_PATH: 'AMA/ContactID/%Y%m%d'
    CONTACT_ID__EXTRACT_ORGMANAGER__CACHE_OUTPUT_ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__EXTRACT_ORGMANAGER__CACHE_OUTPUT_ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__EXTRACT_ORGMANAGER__CACHE_OUTPUT_SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__EXTRACT_ORGMANAGER__CACHE_OUTPUT_BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'
    CONTACT_ID__EXTRACT_ORGMANAGER__CACHE_OUTPUT_FILES: 'Users_%Y%m%d.csv'
    CONTACT_ID__EXTRACT_ORGMANAGER__CACHE_OUTPUT_INCLUDE_DATESTAMP: 'false'

    #CONTACT_ID__EXTRACT_SEED_FILES__TASK_CLASS: 'datalabs.etl.s3.extract.S3FileExtractorTask'
    CONTACT_ID__EXTRACT_SEED_FILES__BASE_PATH: 'AMA/ContactID'
    CONTACT_ID__EXTRACT_SEED_FILES__FILES: 'SFMC_FlatFile_seed.csv, Users_seed.csv'
    CONTACT_ID__EXTRACT_SEED_FILES__INCLUDE_DATESTAMP: 'false'
    CONTACT_ID__EXTRACT_SEED_FILES__ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__EXTRACT_SEED_FILES__ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__EXTRACT_SEED_FILES__SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__EXTRACT_SEED_FILES__BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'

    CONTACT_ID__EXTRACT_SEED_FILES__CACHE_OUTPUT_CLASS: 'datalabs.etl.dag.cache.s3.S3TaskDataCache'
    CONTACT_ID__EXTRACT_SEED_FILES__CACHE_OUTPUT_BASE_PATH: 'AMA/ContactID/%Y%m%d'
    CONTACT_ID__EXTRACT_SEED_FILES__CACHE_OUTPUT_ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__EXTRACT_SEED_FILES__CACHE_OUTPUT_ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__EXTRACT_SEED_FILES__CACHE_OUTPUT_SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__EXTRACT_SEED_FILES__CACHE_OUTPUT_BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'
    CONTACT_ID__EXTRACT_SEED_FILES__CACHE_OUTPUT_FILES: 'SFMC_FlatFile_seed.csv, Users_seed.csv'
    CONTACT_ID__EXTRACT_SEED_FILES__CACHE_OUTPUT_INCLUDE_DATESTAMP: 'false'

    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_INPUT_CLASS: 'datalabs.etl.dag.cache.s3.S3TaskDataCache'
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_INPUT_BASE_PATH: 'AMA/ContactID/%Y%m%d'
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_INPUT_FILES: 'SFMC_FLATFILE_%Y%m%d.txt, SFMC_FlatFile_seed.csv, Users_%Y%m%d.csv, Users_seed.csv'
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_INPUT_INCLUDE_DATESTAMP: 'false'
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_INPUT_ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_INPUT_ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_INPUT_SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_INPUT_BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'

    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_OUTPUT_CLASS: 'datalabs.etl.dag.cache.s3.S3TaskDataCache'
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_OUTPUT_BASE_PATH: 'AMA/ContactID/%Y%m%d'
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_OUTPUT_ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_OUTPUT_ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_OUTPUT_SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_OUTPUT_BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_OUTPUT_FILES: 'SFMC_DataLabs_VALID_FlatFile_%Y%m%d.csv, SFMC_DataLabs_OrgManager_Users_%Y%m%d.csv'
    CONTACT_ID__ASSIGN_EXISTING_CONTACT_IDS__CACHE_OUTPUT_INCLUDE_DATESTAMP: 'false'

    #CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS_CLASS: 'datalabs.etl.s3.extract.S3FileExtractorTask'
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__BASE_PATH: 'AMA/ContactID/%Y%m%d'
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__FILES: 'SFMC_DataLabs_VALID_FlatFile_%Y%m%d.csv, SFMC_DataLabs_OrgManager_Users_%Y%m%d.csv, API_Orders.csv, Active_Subscription.csv'
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__INCLUDE_DATESTAMP: 'false'
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'

    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__CACHE_OUTPUT_CLASS: 'datalabs.etl.dag.cache.s3.S3TaskDataCache'
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__CACHE_OUTPUT_BASE_PATH: 'AMA/ContactID/%Y%m%d'
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__CACHE_OUTPUT_ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__CACHE_OUTPUT_ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__CACHE_OUTPUT_SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__CACHE_OUTPUT_BUCKET: 'ama-hsg-datalabs-datalake-processing-onprem'
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__CACHE_OUTPUT_FILES: 'SFMC_DataLabs_VALID_FlatFile_%Y%m%d.csv, SFMC_DataLabs_Advantage_ActiveSubscription_%Y%m%d.csv, SFMC_DataLabs_OrgManager_Users_%Y%m%d.csv, SFMC_DataLabs_Advantage_APIOrders_%Y%m%d.csv'
    CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS__CACHE_OUTPUT_INCLUDE_DATESTAMP: 'false'

    #CONTACT_ID__MERGE_AND_GENERATE_NEW_IDS_CLASS: 'datalabs.etl.s3.extract.S3FileExtractorTask'
    CONTACT_ID__UPDATE_SEED_FILES__BASE_PATH: 'AMA/ContactID/%Y%m%d'
    CONTACT_ID__UPDATE_SEED_FILES__FILES: 'SFMC_DataLabs_VALID_FlatFile_%Y%m%d.csv, SFMC_DataLabs_OrgManager_Users_%Y%m%d.csv'
    CONTACT_ID__UPDATE_SEED_FILES__INCLUDE_DATESTAMP: 'false'
    CONTACT_ID__UPDATE_SEED_FILES__ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__UPDATE_SEED_FILES__ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__UPDATE_SEED_FILES__SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__UPDATE_SEED_FILES__BUCKET: 'ama-hsg-datalabs-datalake-processing-onprem'

    CONTACT_ID__UPDATE_SEED_FILES__INPUT_CACHE_OUTPUT_CLASS: 'datalabs.etl.dag.cache.s3.S3TaskDataCache'
    CONTACT_ID__UPDATE_SEED_FILES__INPUT_CACHE_OUTPUT_BASE_PATH: 'AMA/ContactID'
    CONTACT_ID__UPDATE_SEED_FILES__INPUT_CACHE_OUTPUT_ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__UPDATE_SEED_FILES__INPUT_CACHE_OUTPUT_ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__UPDATE_SEED_FILES__INPUT_CACHE_OUTPUT_SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__UPDATE_SEED_FILES__INPUT_CACHE_OUTPUT_BUCKET: 'ama-hsg-datalabs-datalake-ingestion-onprem'
    CONTACT_ID__UPDATE_SEED_FILES__OUTPUT_CACHE_FILES: 'SFMC_FlatFile_seed.csv, Users_seed.csv'
    CONTACT_ID__UPDATE_SEED_FILES__CACHE_INCLUDE_DATESTAMP: 'false'

    CONTACT_ID__DELIVER_OUTPUT_FILES__INPUT_CACHE_CLASS: 'datalabs.etl.dag.cache.s3.S3TaskDataCache'
    CONTACT_ID__DELIVER_OUTPUT_FILES__INPUT_CACHE_BASE_PATH: 'AMA/ContactID/%Y%m%d'
    CONTACT_ID__DELIVER_OUTPUT_FILES__INPUT_CACHE_ENDPOINT_URL: 'https://hsg-data-labs-minio.apps.openshifttest.ama-assn.org'
    CONTACT_ID__DELIVER_OUTPUT_FILES__INPUT_CACHE_ACCESS_KEY: ${ACCESS_KEY}
    CONTACT_ID__DELIVER_OUTPUT_FILES__INPUT_CACHE_SECRET_KEY: ${SECRET_KEY}
    CONTACT_ID__DELIVER_OUTPUT_FILES__INPUT_CACHE_BUCKET: 'ama-hsg-datalabs-datalake-processing-onprem'
    CONTACT_ID__DELIVER_OUTPUT_FILES__INPUT_CACHE_INPUT_FILES: 'SFMC_DataLabs_VALID_FlatFile_%Y%m%d.csv, SFMC_DataLabs_Advantage_ActiveSubscription_%Y%m%d.csv, SFMC_DataLabs_OrgManager_Users_%Y%m%d.csv, SFMC_DataLabs_Advantage_APIOrders_%Y%m%d.csv'
    CONTACT_ID__DELIVER_OUTPUT_FILES__OUTPUT_CACHE_BASE_PATH: '/DataLabs/To_SFMC_SFTP/'
    CONTACT_ID__DELIVER_OUTPUT_FILES__OUTPUT_CACHE_FILES: 'SFMC_DataLabs_VALID_FlatFile_%Y%m%d.csv, SFMC_DataLabs_Advantage_ActiveSubscription_%Y%m%d.csv, SFMC_DataLabs_OrgManager_Users_%Y%m%d.csv, SFMC_DataLabs_Advantage_APIOrders_%Y%m%d.csv'
    CONTACT_ID__DELIVER_OUTPUT_FILES__OUTPUT_CACHE_HOST: 'eft.ama-assn.org'
    CONTACT_ID__DELIVER_OUTPUT_FILES__OUTPUT_CACHE_USERNAME: ${EFT_USERNAME}
    CONTACT_ID__DELIVER_OUTPUT_FILES__OUTPUT_CACHE_PASSWORD: ${EFT_PASSWORD}
    CONTACT_ID__DELIVER_OUTPUT_FILES__CACHE_INCLUDE_DATESTAMP: 'false'
