CREATE TABLE IF NOT EXISTS samples(
    sample_id INTEGER NOT NULL,
    row_id INTEGER NOT NULL,
    survey_month INTEGER,
    survey_year INTEGER,
    survey_type VARCHAR,
    sample_source VARCHAR,
    me VARCHAR,
    entity_id INTEGER,
    first_name VARCHAR,
    middle_name VARCHAR,
    last_name VARCHAR,
    suffix VARCHAR,
    polo_comm_id INTEGER,
    polo_mailing_line_1 VARCHAR,
    polo_mailing_line_2, VARCHAR,
    polo_city VARCHAR,
    polo_state VARCHAR,
    polo_zip VARCHAR,
    phone_comm_id INTEGER,
    telephone_number VARCHAR,
    prim_spec_cd VARCHAR,
    description_pe_cd VARCHAR,
    fax_number VARCHAR,

    UNIQUE(sample_id, row_id)
);

CREATE TABLE IF NOT EXISTS results_standard(
    sample_id INTEGER REFERENCES samples(sample_id),
    row_id INTEGER NOT NULL,
    physician_me_number VARCHAR,
    physician_first_name VARCHAR,
    physician_middle_name VARCHAR,
    physician_last_name VARCHAR,
    suffix VARCHAR,
    degree VARCHAR,
    office_address_line_1 VARCHAR,
    office_address_line_2 VARCHAR,
    office_address_city VARCHAR,
    office_address_state VARCHAR,
    office_address_zip VARCHAR,
    office_address_verified_updated INTEGER,
    office_telephone VARCHAR,
    office_phone_verified_updated INTEGER,
    office_fax VARCHAR,
    office_fax_verified_updated INTEGER,
    specialty VARCHAR,
    specialty_updated VARCHAR,
    present_employment_code VARCHAR,
    present_employment_updated INTEGER,
    comments VARCHAR,
    source VARCHAR,
    source_date DATE,
    phone_status VARCHAR,
    address_status VARCHAR,
    pe_status VARCHAR,
    fax_status VARCHAR,

    UNIQUE(sample_id, row_id)
);

CREATE TABLE IF NOT EXISTS results_validation(
    sample_id INTEGER REFERENCES samples(sample_id),
    row_id INTEGER NOT NULL,
    study_cd VARCHAR,
    me_no VARCHAR,
    fname VARCHAR,
    mname VARCHAR,
    lname VARCHAR,
    suffix VARCHAR,
    degree VARCHAR,
    lable_name VARCHAR,
    office_phone VARCHAR,
    polo_addr_line_0 VARCHAR,
    polo_addr_line_1 VARCHAR,
    polo_addr_line_2 VARCHAR,
    polo_city VARCHAR,
    polo_state VARCHAR,
    polo_zip VARCHAR,
    polo_zipext VARCHAR,
    original_phone VARCHAR,
    correct_phone VARCHAR,
    reason_phone_incorrect INTEGER,
    reason_phone_other INTEGER,
    captured_number VARCHAR,
    correct_address VARCHAR,
    reason_addr_incorrect INTEGER,
    reason_addr_other INTEGER,
    no_longer_at_addr_comment VARCHAR,
    captured_add0 VARCHAR,
    captured_add1 VARCHAR,
    captured_add2 VARCHAR,
    captured_city VARCHAR,
    captured_state VARCHAR,
    captured_zip VARCHAR,
    captured_zipext VARCHAR,
    lastcall DATE,
    adcid VARCHAR,
    secondattempt VARCHAR,
    result_of_call VARCHAR,
    phone_status1 VARCHAR,
    address_status1 VARCHAR,

    UNIQUE(sample_id, row_id)
);