''' DAG definition for the DAG Scheduler. '''
from   datalabs.etl.dag.dag import DAG
from   datalabs.etl.archive.transform import ZipTransformerTask
from   datalabs.etl.cpt.release.transform import ReleaseTypesTransformerTask  # , ReleaseTransformerTask
from   datalabs.etl.cpt.api.load import CPTRelationalTableLoaderTask
from   datalabs.etl.cpt.api.transform import \
    ReleasesTransformerTask, \
    CodesTransformerTask, \
    ReleaseCodeMappingTransformerTask, \
    ShortDescriptorTransformerTask, \
    MediumDescriptorTransformerTask, \
    LongDescriptorTransformerTask, \
    ModifierTypeTransformerTask, \
    ModifierTransformerTask, \
    ConsumerDescriptorTransformerTask, \
    ClinicianDescriptorCodeMappingTransformerTask, \
    PLADetailsTransformerTask, \
    ManufacturerTransformerTask, \
    ManufacturerCodeMappingTransformerTask, \
    LabTransformerTask, \
    LabCodeMappingTransformerTask
from   datalabs.etl.cpt.ingest.extract import CPTTextDataExtractorTask
from   datalabs.etl.orm.load import ORMLoaderTask
from   datalabs.etl.parse.transform import ParseToCSVTransformerTask


class CPTDAG(DAG):
    # CREATE_CURRENT_RELEASE: ReleaseTransformerTask
    CREATE_RELEASE_TYPES: ReleaseTypesTransformerTask
    LOAD_RELEASE_TYPES: ORMLoaderTask
    PARSE_TEXT_FILES: ParseToCSVTransformerTask
    CREATE_RELEASE_TABLE: ReleasesTransformerTask
    CREATE_CODES_TABLE: CodesTransformerTask
    CREATE_RELEASE_CODE_MAPPING_TABLE: ReleaseCodeMappingTransformerTask
    CREATE_SHORT_DESCRIPTOR_TABLE: ShortDescriptorTransformerTask
    CREATE_MEDIUM_DESCRIPTOR_TABLE: MediumDescriptorTransformerTask
    CREATE_LONG_DESCRIPTOR_TABLE: LongDescriptorTransformerTask
    CREATE_MODIFIER_TYPE_TABLE: ModifierTypeTransformerTask
    CREATE_MODIFIER_TABLE: ModifierTransformerTask
    CREATE_CONSUMER_DESCRIPTOR_TABLE: ConsumerDescriptorTransformerTask
    CREATE_CLINICIAN_DESCRIPTOR_TABLE: ClinicianDescriptorCodeMappingTransformerTask
    CREATE_PLA_DETAILS_TABLE: PLADetailsTransformerTask
    CREATE_MANUFACTURER_TABLE: ManufacturerTransformerTask
    CREATE_MANUFACTURER_CODE_MAPPING_TABLE: ManufacturerCodeMappingTransformerTask
    CREATE_LAB_TABLE: LabTransformerTask
    CREATE_LAB_CODE_MAPPING_TABLE: LabCodeMappingTransformerTask
    CREATE_PDFS_ZIP: ZipTransformerTask
    LOAD_TABLES: ORMLoaderTask


CPTDAG.CREATE_RELEASE_TYPES >> CPTDAG.LOAD_RELEASE_TYPES

CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_RELEASE_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_CODES_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_RELEASE_CODE_MAPPING_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_SHORT_DESCRIPTOR_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_MEDIUM_DESCRIPTOR_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_LONG_DESCRIPTOR_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_MODIFIER_TYPE_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_MODIFIER_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_CONSUMER_DESCRIPTOR_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_CLINICIAN_DESCRIPTOR_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_PLA_DETAILS_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_MANUFACTURER_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_MANUFACTURER_CODE_MAPPING_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_LAB_TABLE
CPTDAG.PARSE_TEXT_FILES >> CPTDAG.CREATE_LAB_CODE_MAPPING_TABLE

# CPTDAG.CREATE_CURRENT_RELEASE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_RELEASE_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_CODES_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_RELEASE_CODE_MAPPING_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_SHORT_DESCRIPTOR_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_MEDIUM_DESCRIPTOR_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_LONG_DESCRIPTOR_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_MODIFIER_TYPE_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_MODIFIER_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_CONSUMER_DESCRIPTOR_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_CLINICIAN_DESCRIPTOR_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_PLA_DETAILS_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_MANUFACTURER_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_MANUFACTURER_CODE_MAPPING_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_LAB_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.CREATE_LAB_CODE_MAPPING_TABLE >> CPTDAG.LOAD_TABLES
CPTDAG.LOAD_RELEASE_TYPES >> CPTDAG.LOAD_TABLES
