#!/bin/bash


for FUNCTION_NAME in CPTStressGetDescriptor CPTStressGetDescriptors CPTStressGetConsumerDescriptor CPTStressGetConsumerDescriptors CPTStressGetClinicianDescriptors CPTStressGetAllClinicianDescriptors CPTStressGetModifier CPTStressGetModifiers CPTStressGetPLADetails CPTStressGetAllPLADetails CPTStressGetLatestPDFs CPTStressGetReleases CPTStressDefault CPTStressConvert CPTStressLoad; do
  aws --no-verify-ssl lambda update-function-code --function-name $FUNCTION_NAME --s3-bucket ama-hsg-datalabs-lambda-code-sandbox --s3-key CPT/CPT.zip
done
