#!/bin/bash

set -ex

PROJECT="${PROJECT:-DataLake}"
ENVIRONMENT="${ENVIRONMENT:-sbx}"
CODE_BUCKET="${CODE_BUCKET:-ama-${ENVIRONMENT}-datalake-lambda-us-east-1}"

FUNCTION_DATA="HelloWorldJavaDAG:DAG.zip
               HelloWorldJavaTask:Task.jar"

for datum in ${FUNCTION_DATA}; do
    function="${PROJECT}-${ENVIRONMENT}-${datum%%:*}"
    bundle=HelloWorldJava/${datum#*:}
    aws lambda update-function-code --function-name ${function} --s3-bucket ${CODE_BUCKET} --s3-key ${bundle} || exit $?
done
