#!/bin/bash


SCRIPT_PATH=`realpath $0`
SCRIPT_BASE_PATH=`dirname $SCRIPT_PATH`
. ${SCRIPT_BASE_PATH}/../Source/Bash/datalabs/environment/setup/venv.sh
MASTER_BUILD_PATH=${SCRIPT_BASE_PATH}/../Build/Master
PYTHON_SOURCE_PATH=${SCRIPT_BASE_PATH}/../Source/Python
PROJECT=
FORCE_OVERWRITE=false
PROJECT_BUILD_PATH=
PROJECT_ENVIRONMENT_PATH=
ZIP_BUNDLE=


main() {
    process_arguments $*

    BUNDLE_PATH=${PROJECT_BUILD_PATH}/app
    BUNDLE_ZIP_PATH=${PROJECT_BUILD_PATH}/app.zip

    create_bundle_directory $BUNDLE_PATH

    copy_source_files $BUNDLE_PATH

    copy_dependency_files $BUNDLE_PATH

    if [[ "$ZIP_BUNDLE" == true ]]; then
        zip_bundle_directory $BUNDLE_PATH $BUNDLE_ZIP_PATH
    fi
}

process_arguments() {
    while (( "$#" )); do
      case "$1" in
        -h|--help)
            print_usage
            exit 0
            ;;
        -s|--serverless)
            ZIP_BUNDLE=true
            shift
            ;;
        -f|--force)
            FORCE_OVERWRITE=true
            shift
            ;;
        *)
            PROJECT=$1
            shift
            shift
            ;;
      esac
    done

    if [[ "$SCHEMA" == "" ]]; then
        echo "Error: The database schema name was not specified."
        exit 1
    fi

    if [[ "$MODEL_MODULE" == "" ]]; then
        echo "Error: The model module was not specified."
        exit 1
    fi

    if [[ "$PROJECT" == "" ]]; then
        echo "Error: The name of the target project was not specified."
        exit 1
    fi

    PROJECT_BUILD_PATH=${SCRIPT_BASE_PATH}/../Build/${PROJECT}
    PROJECT_ENVIRONMENT_PATH=${SCRIPT_BASE_PATH}/../Environment/${PROJECT}
}


create_bundle_directory() {
    BUNDLE_PATH=$1

    if [[ -d $BUNDLE_PATH && "$FORCE_OVERWRITE" == false ]]; then
        real_path=`realpath ${BUNDLE_PATH}`
        echo "Error: Bundle directory ${real_path} already exists."
        exit 2
    fi

    # rm -rf $PROJECT_BUNDLE_PATH

    echo "Creating bundle directory ${real_path}."
    mkdir -p 
}


copy_source_files() {
    BUNDLE_PATH=$1
}


copy_dependency_files() {
    BUNDLE_PATH=$2
}


zip_bundle_directory() {
    BUNDLE_PATH=$1
    BUNDLE_ZIP_PATH=$2
}


print_usage() {
    echo "Usage: create-database-config [OPTION]... <project>"
    echo "Setup an initial Alembic configuration in ...Build/<project>/."
    echo
    echo "Options:"
    echo "  -h|--help                  Print usage."
    echo "  -s|--schema <schema>       Set the database schema name to use for tables."
    echo "  -m|--model-module <module> Set the fully-qualified Python module name that"
    echo "                             holds the SQLAlchemy declaritive base definition."
    echo "  -f, --force                Overwrite any directories or files that are created."
}




# echo "Executing create_pkg.sh..."

# cd $path_cwd
# dir_name=lambda_dist_pkg/
# mkdir $dir_name

# # Create and activate virtual environment...
# virtualenv -p $runtime env_$function_name
# source $path_cwd/env_$function_name/bin/activate

# # Installing python dependencies...
# FILE=$path_cwd/lambda_function/requirements.txt

# if [ -f "$FILE" ]; then
#   echo "Installing dependencies..."
#   echo "From: requirement.txt file exists..."
#   pip install -r "$FILE"

# else
#   echo "Error: requirement.txt does not exist!"
# fi

# # Deactivate virtual environment...
# deactivate

# # Create deployment package...
# echo "Creating deployment package..."
# cd env_$function_name/lib/$runtime/site-packages/
# cp -r . $path_cwd/$dir_name
# cp -r $path_cwd/lambda_function/ $path_cwd/$dir_name

# # Removing virtual environment folder...
# echo "Removing virtual environment folder..."
# rm -rf $path_cwd/env_$function_name

# echo "Finished script execution!"