#!/usr/bin/env bash


SCRIPT_PATH=`realpath $0`
SCRIPT_BASE_PATH=`dirname $SCRIPT_PATH`
RUN="${SCRIPT_BASE_PATH}/run.py python"


main() {
    $RUN ${SCRIPT_BASE_PATH}/clear_task.py "$@"
}


main "$@"
