#!/bin/bash


main() {
    dag=$1
    execution_time=$2  # 2021-09-29 22:45:00

    aws dynamodb delete-item --table-name DataLake-dag-state-dev \
        --key '{"name": {"S": "'${dag}'"}, "execution_time": {"S": "'"${execution_time}"'"}}'

}

main "$1" "$2"
