#!/bin/bash


main() {
    dag=$1
    execution_time=$2  # 2021-09-29 22:45:00
    environment=${3:-dev}

    aws dynamodb delete-item --table-name DataLake-dag-state-${environment} \
        --key '{"name": {"S": "'${dag}'"}, "execution_time": {"S": "'"${execution_time}"'"}}'

}

main "$1" "$2" "$3"
