#!/bin/bash


SCRIPT_PATH=`realpath $0`
SCRIPT_BASE_PATH=`dirname $SCRIPT_PATH`
RUN="${SCRIPT_BASE_PATH}/run.py python"


main() {
    $RUN ${SCRIPT_BASE_PATH}/delete_snyk_branches.py "$@"
}


main "$@"
