#!/usr/bin/env bash


SCRIPT_PATH=`realpath $0`
SCRIPT_BASE_PATH=`dirname $SCRIPT_PATH`
RUN="${SCRIPT_BASE_PATH}/run.py /usr/bin/python3"


main() {
    $RUN ${SCRIPT_BASE_PATH}/run_endpoint.py "$@"
}


main "$@"
