#!/usr/bin/env bash


SCRIPT_PATH=`realpath $0`
SCRIPT_BASE_PATH=`dirname $SCRIPT_PATH`
RUN="${SCRIPT_BASE_PATH}/run.py python"
DEPDENCIES_CLASSPATH=$(mvn -f ${SCRIPT_BASE_PATH}/../pom.xml dependency:build-classpath | grep -v "[INFO]")
export CLASSPATH=${SCRIPT_BASE_PATH}/../target/DataLabs-dev.jar:${DEPDENCIES_CLASSPATH}


main() {
    $RUN ${SCRIPT_BASE_PATH}/run_task.py "$@" java
}


main "$@"
