#!/bin/bash

set -ex


SCRIPT_PATH=`realpath $0`
SCRIPT_BASE_PATH=`dirname $SCRIPT_PATH`
. ${SCRIPT_BASE_PATH}/../Source/Bash/environment/python/setup.sh
PROJECT_NAME=


main() {
    process_arguments "$@"

    create_environment_directory

    link_to_requirements_file

    setup_virtual_environment
}


process_arguments() {
    while (( "$#" )); do
      case "$1" in
        -h|--help)
            print_usage
            exit 0
            ;;
        *)
            PROJECT_NAME=$1
            shift
            ;;
      esac
    done

    if [[ "$PROJECT_NAME" == "" ]]; then
        echo "Error: The name of the project to create was not specified."
        exit 1
    fi
}


print_usage() {
    echo "Usage: setup-virtual-environment <project name> [-h|--help]"
}


create_environment_directory() {
    mkdir -p ${SCRIPT_BASE_PATH}/../Environment/${PROJECT_NAME}
}


link_to_requirements_file() {
    BUILD_REQUIREMENTS=${SCRIPT_BASE_PATH}/../Build/${PROJECT_NAME}/requirements.txt
    ENVIRONMENT_REQUIREMENTS=${SCRIPT_BASE_PATH}/../Environment/${PROJECT_NAME}/requirements.txt

    rm -f ${ENVIRONMENT_REQUIREMENTS}
    ln -s ${BUILD_REQUIREMENTS} ${ENVIRONMENT_REQUIREMENTS}
}


setup_virtual_environment() {
    setup_python_virtual_environment ${SCRIPT_BASE_PATH}/../Environment/${PROJECT_NAME}
}

main "$@"
