#!/bin/bash

SCRIPT=`realpath $0`
SCRIPT_PATH=`dirname $SCRIPT`

# import Bash function:  setup_python_virtual_environment
. ${SCRIPT_PATH}/../Source/Bash/datalabs/environment/setup.sh


main() {
    check_user

    check_os_version

    # install_drivers

    install_tools

    clean_up
}


check_user() {
    user=$(whoami)

    if [[ $user != 'root' ]]; then
        echo This script must be run as the root user
        exit 1
    fi
}


check_os_version() {
    . /etc/os-release
    echo Running $PRETTY_NAME

    if [[ $NAME != 'Ubuntu' ]]; then
        echo Unsupported OS $NAME
        exit 2
    elif [[ $VERSION_ID != '18.04' ]]; then
        echo Unsupported OS version $VERSION_ID
        exit 2
    fi
}


install_drivers() {
    install_msodbcsql17_driver
}


install_tools() {
    install_core_dependencies

    install_python_tools

    # install_node
}


clean_up() {
    apt autoremove -y
}


install_msodbcsql17_driver() {
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
    curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
    apt update

    ACCEPT_EULA=Y apt install -y msodbcsql17
}


install_core_dependencies() {
    apt update

    echo '* libraries/restart-without-asking boolean true' | sudo debconf-set-selections

    apt install -y software-properties-common build-essential curl
}


install_python_tools() {
    install_pip

    install_python3_7

    configure_default_python3

    install_venv

    # install_pipenv

    install_dev_libraries

    create_base_virtual_environment
}


install_node() {
    curl -sL https://deb.nodesource.com/setup_10.x -o /tmp/nodesource_setup.sh

    bash /tmp/nodesource_setup.sh

    rm /tmp/nodesource_setup.sh

    apt install -y nodejs
}


install_pip() {
    apt install -y python3-pip

    python3 -m pip install --trusted-host pypi.org --upgrade pip
}


install_python3_7() {
    add-apt-repository -y ppa:deadsnakes/ppa

    apt install -y python3.7
}


configure_default_python3() {
    # Python 3.6 is pre-installed with the Ubuntu WSL
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 0
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1

    update-alternatives --set python3 /usr/bin/python3.7
}


install_venv() {
    apt install -y python3.7-venv
}


install_pipenv() {
    python3 -m pip install pipenv
}


install_dev_libraries() {
    apt install -y python3.7-dev unixodbc-dev
}


create_base_virtual_environment() {
    setup_python_virtual_environment Environment/Master
}


main
