#!/bin/bash


SCRIPT_PATH=`realpath $0`
SCRIPT_BASE_PATH=`dirname $SCRIPT_PATH`
. ${SCRIPT_BASE_PATH}/../Source/Bash/datalabs/environment/setup/venv.sh
PROJECT_NAME=


main() {
    process_arguments $*

    create_environment_directory

    link_to_requirements_file

    setup_python_virtual_environment ${SCRIPT_BASE_PATH}/../Environment/${PROJECT_NAME}
}


process_arguments() {
    while (( "$#" )); do
      case "$1" in
        -h|--help)
            print_usage
            exit 0
            ;;
        *)
            PROJECT_NAME=$1
            shift
            ;;
      esac
    done

    if [[ "$PROJECT_NAME" == "" ]]; then
        echo "Error: The name of the project to create was not specified."
        exit 1
    fi
}


print_usage() {
    echo "Usage: setup-virtual-environment <project name> [-h|--help]"
}


create_environment_directory() {
    mkdir ${SCRIPT_BASE_PATH}/../Environment/${PROJECT_NAME}
}

link_to_requirements_file() {
    ln -s ${SCRIPT_BASE_PATH}/../Build/${PROJECT_NAME}/requirements.txt ${SCRIPT_BASE_PATH}/../Environment/${PROJECT_NAME}/requirements.txt
}

main $*