#!/bin/bash

SCRIPT=`realpath $0`
SCRIPT_PATH=`dirname $SCRIPT`

. ${SCRIPT_PATH}/../Source/Bash/environment/development/setup.sh


main() {
    check_user

    check_os_version

    # install_drivers

    install_tools

    clean_up
}

check_user() {
    user=$(whoami)

    if [[ $user != 'root' ]]; then
        echo This script must be run as the root user
        exit 1
    fi
}


check_os_version() {
    . /etc/os-release
    echo Running $PRETTY_NAME

    if [[ $NAME != 'Ubuntu' ]]; then
        echo Unsupported OS $NAME
        exit 2
    elif [[ $VERSION_ID != '18.04' ]]; then
        echo Unsupported OS version $VERSION_ID
        exit 2
    fi
}


install_drivers() {
    install_msodbcsql17_driver
}


install_tools() {
    echo "### Installing core dependencies ###"
    install_core_dependencies

    echo "### Installing Python tools ###"
    install_python_tools

    # install_node

    echo "### Installing AWS tools ###"
    install_aws_tools
}


clean_up() {
    apt autoremove -y
}


main
