#!/bin/bash


SCRIPT_PATH=`realpath $0`
SCRIPT_BASE_PATH=`dirname $SCRIPT_PATH`
. ${SCRIPT_BASE_PATH}/../Source/Bash/datalabs/environment/setup.sh
PROJECT_NAME=


main() {
    process_arguments $*

    bash --rcfile <(echo ". ~/.bashrc; . ${SCRIPT_BASE_PATH}/../Environment/${PROJECT_NAME}/bin/activate")
}


process_arguments() {
    while (( "$#" )); do
      case "$1" in
        -h|--help)
            print_usage
            exit 0
            ;;
        *)
            PROJECT_NAME=$1
            shift
            ;;
      esac
    done

    if [[ "$PROJECT_NAME" == "" ]]; then
        echo "Error: The name of the project to create was not specified."
        exit 1
    fi
}


print_usage() {
    echo "Usage: start-virtual-environment <project name> [-h|--help]"
}


main $*