#!/bin/bash

SCRIPT=`realpath $0`
SCRIPT_PATH=`dirname $SCRIPT`

. ${SCRIPT_PATH}/../Source/Bash/environment/development/setup.sh


main() {
    check_user

    check_os_version

    remove_tools

    # remove_drivers
}


check_user() {
    user=$(whoami)

    if [[ $user != 'root' ]]; then
        echo This script must be run as the root user
        exit 1
    fi
}


check_os_version() {
    . /etc/os-release
    echo Running $PRETTY_NAME

    if [[ $NAME != 'Ubuntu' ]]; then
        echo Unsupported OS $NAME
        exit 2
    elif [[ $VERSION_ID != '18.04' ]]; then
        echo Unsupported OS version $VERSION_ID
        exit 2
    fi
}


remove_tools() {
    # remove_node

    remove_python_tools

    remove_core_dependencies
}


remove_drivers() {
    remove_msodbcsql17_driver
}


main
