""" SQLAlchemy models for CPT """
import sqlalchemy as sa
from   sqlalchemy.ext.declarative import declarative_base

from   datalabs.sqlalchemy import metadata

Base = declarative_base(metadata=metadata())  # pylint: disable=invalid-name


class Contact(Base):
    __tablename__ = 'contact'

    id = sa.Column(sa.Integer, primary_key=True)
    record_sequence = sa.Column(sa.String)
    EMPPID = sa.Column(sa.Integer)
    business = sa.Column(sa.String)
    name = sa.Column(sa.String)
    business_title = sa.Column(sa.String)
    business_name = sa.Column(sa.String)
    address_1 = sa.Column(sa.String)
    address_2 = sa.Column(sa.String)
    address_3 = sa.Column(sa.String)
    city = sa.Column(sa.String)
    state = sa.Column(sa.String)
    zipcode = sa.Column(sa.String)
    country = sa.Column(sa.String)
    DPCCODE = sa.Column(sa.String)
    DPCCHECK = sa.Column(sa.String)
    CARRTE = sa.Column(sa.String)
    list_keys = sa.Column(sa.String)
    gender = sa.Column(sa.String)
    SUP_DMACHOICE = sa.Column(sa.String)
    SUP_DM_REGION = sa.Column(sa.String)
    SUP_DNMFLAG = sa.Column(sa.String)
    SUP_DNRFLAG = sa.Column(sa.String)
    SUP_DNCFLAG = sa.Column(sa.String)
    SOURCE_ORD = sa.Column(sa.String)
    TITLE_DESC = sa.Column(sa.String)
    PREFIX_DESC = sa.Column(sa.String)
    day_phone = sa.Column(sa.String)
    evening_phone = sa.Column(sa.String)
    fax = sa.Column(sa.String)
    email = sa.Column(sa.String)
    EMAIL_MORA = sa.Column(sa.String)
    industry_description = sa.Column(sa.String)
    SUP_DM = sa.Column(sa.String)
    SUP_TM = sa.Column(sa.String)
    SUP_EM = sa.Column(sa.String)
    is_physician = sa.Column(sa.Boolean)
    is_member = sa.Column(sa.Boolean)
    primary_specialty = sa.Column(sa.String)
    secondary_specialty = sa.Column(sa.String)
    hs_contact_id = sa.Column(sa.String, nullable=False, unique=True)
    email_last_validated = sa.Column(sa.Date, nullable=False)


"""
COLUMNS = dict(
    record_sequence="RECSEQ",
    ="EMPPID",
    business="BUSPID",
    name="NAME",
    business_title="BUSTITLE",
    business_name="BUSNAME",
    address_1="ADDR1",
    address_2="ADDR2",
    address_3="ADDR3",
    city="CITY",
    state="STATE",
    zipcode="ZIP",
    country="COUNTRY",
    ="DPCCODE",
    ="DPCCHECK",
    ="CARRTE",
    list_keys="LISTKEY",
    gender="GENDER",
    ="SUP_DMACHOICE",
    ="SUP_DM_REGION",
    "SUP_DNMFLAG",
    ="SUP_DNRFLAG",
    ="SUP_DNCFLAG",
    ="SUP_DNEFLAG",
    ="SOURCE_ORD",
    ="TITLE_DESC",
    ="PREFIX_DESC",
    day_phone="DAY_PHONE",
    evening_phone="EVENING_PHONE",
    fax="FAX_NUMBER",
    email="BEST_EMAIL",
    ="EMAIL_MORA",
    industry_description="INDUSTRY_DESC",
    ="SUP_DM",
    ="SUP_TM",
    ="SUP_EM",
    is_physician="PHYSICIANFLAG",
    is_member="MEMBERFLAG",
    primary_specialty="AIMS_PRIMSPC",
    secondary_specialty="AIMS_SECSPC",
    ="ALL_CHANTYPE",
    ="ALL_LASTODATE",
    ="ALL_ORIGODATE",
    ="ALL_RECNCYMOS",
    ="ALL_RECNCYGR",
    ="ALL_OORDMOS",
    ="ALL_OORDGR",
    ="ALL_FREQNOORD",
    ="ALL_FREQORDGR",
    ="ALL_DOLTOT",
    ="ALL_DOLTOTGR",
    ="ALL_DOLAVG",
    ="ALL_DOLAVGR",
    ="ALL_MAXORDOL",
    ="ALL_ORIGODOL",
    ="ALL_ORIGODOLG",
    ="ALL_ORIGCHAN",
    ="ALL_LASTCHAN",
    ="GEN_SCORE",
    ="GEN_DECILE",
    ="TS_SCORE",
    ="TS_DECILE",
    ="TS_SEGMENT",
    ="TS_RECENCY",
    ="TS_FREQUENCY",
    ="TS_TOTAL_AMT",
    ="TS_AVG_ORDER",
    ="TS_MAX_ORDER",
    ="ALL_LASTODOL",
    ="ALL_LASTODOLG",
    ="CPTA_FREQ",
    ="CPTA_RECENCY",
    ="CPTA_ENDDATE",
    ="CPTA_LASTSLEN",
    ="CPTA_TOTDOL",
    ="CPTA_AVGDOL",
    ="CPTA_LSKUDESC",
    ="CPTA_MAXORDOL",
    ="ONLSUB_LNOLIC",
    ="ONLSUB_SLDATE",
    ="ONLSUB_ELDATE",
    ="ONLSUB_LSTREC",
    ="ONLSUB_FREQ",
    ="ONLSUB_TOTDOL",
    ="ONLSUB_AVGDOL",
    ="ALL_PROMOFREQ",
    ="ALL_MKTDR_BIL",
    ="ALL_MKTDR_CD",
    ="ALL_MKTDR_DOC",
    ="ALL_MKTDR_PRA",
    ="ALL_MKTDR_IMP",
    ="ALL_MKTDR_TRA",
    ="ALL_FTYP_SUB",
    ="ALL_FTYP_PRNT",
    ="ALL_FTYP_DIG",
    ="ALL_FTYP_PRDG",
    ="ALL_FTYP_DATA",
    ="ALL_FTYP_BNDL",
    ="ALL_FTYP_LSUB",
    ="ALL_FTYP_LPRT",
    ="ALL_FTYP_LDIG",
    ="ALL_FTYP_LPRD",
    ="ALL_FTYP_LDTA",
    ="ALL_FTYP_LBND",
    ="ALL_FTYP_FRQ",
    ="ALL_BUYR_TYPE",
    ="OLSUB_DSPNAME",
    ="ALL_LPROD_1",
    ="ALL_LPROD_2",
    ="ALL_FRQPROD_1",
    ="ALL_FRQPROD_2",
    ="ALL_TOT_OPEN",
    ="ALL_TOT_CLICK",
    ="ALL_TOT_BOUNC",
    ="ALL_TOT_UNSBS",
    ="ALL_TOT_SENDS",
    ="ALL_OPEN_RATE",
    ="ALL_CLCK_RATE",
    ="ALL_EMLSOPR_1",
    ="ALL_EMFROPR_1",
    ="ALL_EMLSOPR_2",
    ="ALL_EMFROPR_2",
    ="ALL_MKDR_LSCH",
    ="ALL_MKDR_FRCH",
    ="ALL_MKDR_LSTA",
    ="ALL_MKDR_FRTA",
    ="ALL_PRIMO_LST",
    ="ALL_PRIMO_FRQ",
    ="ALL_DSCAT_LST",
    ="ALL_DSCAT_FRQ",
    ="ALL_AUDNC_LST",
    ="ALL_AUDNC_FRQ",
    ="OLSUB_AUTOREN",
    ="ALL_MK_DRV_DM",
    ="ALL_MK_DRV_CT",
    ="ALL_MK_DRV_WB",
    ="ALL_MK_DRV_TS",
    ="ALL_MK_DRVUSC",
    ="ALL_MK_DRV_EM",
    ="ALL_MK_DRV_LE",
    ="ALL_MK_DRV_FX",
    ="ALL_MK_DRV_SC",
    ="ALL_RESLLR_PR",
    ="ALL_RESLLR_AC",
    ="ALL_EVNT_LEAD",
    ="ALL_SF_LEAD",
    ="ALL_SKU_ORIG",
    ="ALL_SKU_LAST",
    ="ALL_SKU_FRQ",
    ="EM_LASTODATE",
    ="EM_ORIGODATE",
    ="ALL_PROD1",
    ="ALL_PROD2",
    ="ALL_ORG_PROD1",
    ="ALL_ORG_PROD2",
    ="INDUSTRY_DESC.1",
    ="EMAIL.1",
    ="DAY_PHONE.1",
    ="EVENING_PHONE.1",
    hs_contact_id="hs_contact_id",
    email_last_validated="email_last_validated",
)
"""
