""" SQLAlchemy models for CPT """
import sqlalchemy as sa
from   sqlalchemy.ext.declarative import declarative_base

from   datalabs.sqlalchemy import metadata

Base = declarative_base(metadata=metadata())  # pylint: disable=invalid-name


class Contact(Base):
    __tablename__ = 'contact'

    id = sa.Column(sa.Integer, primary_key=True)
    record_sequence = sa.Column(sa.String)
    EMPPID = sa.Column(sa.Integer, nullable=False)
    business = sa.Column(sa.String)
    name = sa.Column(sa.String)
    business_title = sa.Column(sa.String)
    business_name = sa.Column(sa.String)
    address_1 = sa.Column(sa.String)
    address_2 = sa.Column(sa.String)
    address_3 = sa.Column(sa.String)
    city = sa.Column(sa.String)
    state = sa.Column(sa.String)
    zipcode = sa.Column(sa.String)
    country = sa.Column(sa.String)
    DPCCODE = sa.Column(sa.String)
    DPCCHECK = sa.Column(sa.String)
    CARRTE = sa.Column(sa.String)
    list_keys = sa.Column(sa.String)
    gender = sa.Column(sa.String)
    SUP_DMACHOICE = sa.Column(sa.String)
    SUP_DM_REGION = sa.Column(sa.String)
    SUP_DNMFLAG = sa.Column(sa.String)
    SUP_DNRFLAG = sa.Column(sa.String)
    SUP_DNCFLAG = sa.Column(sa.String)
    SOURCE_ORD = sa.Column(sa.String)
    TITLE_DESC = sa.Column(sa.String)
    PREFIX_DESC = sa.Column(sa.String)
    day_phone = sa.Column(sa.String)
    evening_phone = sa.Column(sa.String)
    fax = sa.Column(sa.String)
    email = sa.Column(sa.String, nullable=False)
    EMAIL_MORA = sa.Column(sa.String)
    industry_description = sa.Column(sa.String)
    SUP_DM = sa.Column(sa.String)
    SUP_TM = sa.Column(sa.String)
    SUP_EM = sa.Column(sa.String)
    is_physician = sa.Column(sa.Boolean)
    is_member = sa.Column(sa.Boolean)
    primary_specialty = sa.Column(sa.String)
    secondary_specialty = sa.Column(sa.String)
    ALL_CHANTYPE = sa.Column(sa.String)
    ALL_LASTODATE = sa.Column(sa.String)
    ALL_ORIGODATE = sa.Column(sa.String)
    ALL_RECNCYMOS = sa.Column(sa.String)
    ALL_RECNCYGR = sa.Column(sa.String)
    ALL_OORDMOS = sa.Column(sa.String)
    ALL_OORDGR = sa.Column(sa.String)
    ALL_FREQNOORD = sa.Column(sa.String)
    ALL_FREQORDGR = sa.Column(sa.String)
    ALL_DOLTOT = sa.Column(sa.String)
    ALL_DOLTOTGR = sa.Column(sa.String)
    ALL_DOLAVG = sa.Column(sa.String)
    ALL_DOLAVGR = sa.Column(sa.String)
    ALL_MAXORDOL = sa.Column(sa.String)
    ALL_ORIGODOL = sa.Column(sa.String)
    ALL_ORIGODOLG = sa.Column(sa.String)
    ALL_ORIGCHAN = sa.Column(sa.String)
    ALL_LASTCHAN = sa.Column(sa.String)
    GEN_SCORE = sa.Column(sa.String)
    GEN_DECILE = sa.Column(sa.String)
    TS_SCORE = sa.Column(sa.String)
    TS_DECILE = sa.Column(sa.String)
    TS_SEGMENT = sa.Column(sa.String)
    TS_RECENCY = sa.Column(sa.String)
    TS_FREQUENCY = sa.Column(sa.String)
    TS_TOTAL_AMT = sa.Column(sa.String)
    TS_AVG_ORDER = sa.Column(sa.String)
    TS_MAX_ORDER = sa.Column(sa.String)
    ALL_LASTODOL = sa.Column(sa.String)
    ALL_LASTODOLG = sa.Column(sa.String)
    CPTA_FREQ = sa.Column(sa.String)
    CPTA_RECENCY = sa.Column(sa.String)
    CPTA_ENDDATE = sa.Column(sa.String)
    CPTA_LASTSLEN = sa.Column(sa.String)
    CPTA_TOTDOL = sa.Column(sa.String)
    CPTA_AVGDOL = sa.Column(sa.String)
    CPTA_LSKUDESC = sa.Column(sa.String)
    CPTA_MAXORDOL = sa.Column(sa.String)
    ONLSUB_LNOLIC = sa.Column(sa.String)
    ONLSUB_SLDATE = sa.Column(sa.String)
    ONLSUB_ELDATE = sa.Column(sa.String)
    ONLSUB_LSTREC = sa.Column(sa.String)
    ONLSUB_FREQ = sa.Column(sa.String)
    ONLSUB_TOTDOL = sa.Column(sa.String)
    ONLSUB_AVGDOL = sa.Column(sa.String)
    ALL_PROMOFREQ = sa.Column(sa.String)
    ALL_MKTDR_BIL = sa.Column(sa.String)
    ALL_MKTDR_CD = sa.Column(sa.String)
    ALL_MKTDR_DOC = sa.Column(sa.String)
    ALL_MKTDR_PRA = sa.Column(sa.String)
    ALL_MKTDR_IMP = sa.Column(sa.String)
    ALL_MKTDR_TRA = sa.Column(sa.String)
    ALL_FTYP_SUB = sa.Column(sa.String)
    ALL_FTYP_PRNT = sa.Column(sa.String)
    ALL_FTYP_DIG = sa.Column(sa.String)
    ALL_FTYP_PRDG = sa.Column(sa.String)
    ALL_FTYP_DATA = sa.Column(sa.String)
    ALL_FTYP_BNDL = sa.Column(sa.String)
    ALL_FTYP_LSUB = sa.Column(sa.String)
    ALL_FTYP_LPRT = sa.Column(sa.String)
    ALL_FTYP_LDIG = sa.Column(sa.String)
    ALL_FTYP_LPRD = sa.Column(sa.String)
    ALL_FTYP_LDTA = sa.Column(sa.String)
    ALL_FTYP_LBND = sa.Column(sa.String)
    ALL_FTYP_FRQ = sa.Column(sa.String)
    ALL_BUYR_TYPE = sa.Column(sa.String)
    OLSUB_DSPNAME = sa.Column(sa.String)
    ALL_LPROD_1 = sa.Column(sa.String)
    ALL_LPROD_2 = sa.Column(sa.String)
    ALL_FRQPROD_1 = sa.Column(sa.String)
    ALL_FRQPROD_2 = sa.Column(sa.String)
    ALL_TOT_OPEN = sa.Column(sa.String)
    ALL_TOT_CLICK = sa.Column(sa.String)
    ALL_TOT_BOUNC = sa.Column(sa.String)
    ALL_TOT_UNSBS = sa.Column(sa.String)
    ALL_TOT_SENDS = sa.Column(sa.String)
    ALL_OPEN_RATE = sa.Column(sa.String)
    ALL_CLCK_RATE = sa.Column(sa.String)
    ALL_EMLSOPR_1 = sa.Column(sa.String)
    ALL_EMFROPR_1 = sa.Column(sa.String)
    ALL_EMLSOPR_2 = sa.Column(sa.String)
    ALL_EMFROPR_2 = sa.Column(sa.String)
    ALL_MKDR_LSCH = sa.Column(sa.String)
    ALL_MKDR_FRCH = sa.Column(sa.String)
    ALL_MKDR_LSTA = sa.Column(sa.String)
    ALL_MKDR_FRTA = sa.Column(sa.String)
    ALL_PRIMO_LST = sa.Column(sa.String)
    ALL_PRIMO_FRQ = sa.Column(sa.String)
    ALL_DSCAT_LST = sa.Column(sa.String)
    ALL_DSCAT_FRQ = sa.Column(sa.String)
    ALL_AUDNC_LST = sa.Column(sa.String)
    ALL_AUDNC_FRQ = sa.Column(sa.String)
    OLSUB_AUTOREN = sa.Column(sa.String)
    ALL_MK_DRV_DM = sa.Column(sa.String)
    ALL_MK_DRV_CT = sa.Column(sa.String)
    ALL_MK_DRV_WB = sa.Column(sa.String)
    ALL_MK_DRV_TS = sa.Column(sa.String)
    ALL_MK_DRVUSC = sa.Column(sa.String)
    ALL_MK_DRV_EM = sa.Column(sa.String)
    ALL_MK_DRV_LE = sa.Column(sa.String)
    ALL_MK_DRV_FX = sa.Column(sa.String)
    ALL_MK_DRV_SC = sa.Column(sa.String)
    ALL_RESLLR_PR = sa.Column(sa.String)
    ALL_RESLLR_AC = sa.Column(sa.String)
    ALL_EVNT_LEAD = sa.Column(sa.String)
    ALL_SF_LEAD = sa.Column(sa.String)
    ALL_SKU_ORIG = sa.Column(sa.String)
    ALL_SKU_LAST = sa.Column(sa.String)
    ALL_SKU_FRQ = sa.Column(sa.String)
    EM_LASTODATE = sa.Column(sa.String)
    EM_ORIGODATE = sa.Column(sa.String)
    ALL_PROD1 = sa.Column(sa.String)
    ALL_PROD2 = sa.Column(sa.String)
    ALL_ORG_PROD1 = sa.Column(sa.String)
    ALL_ORG_PROD2 = sa.Column(sa.String)
    industry_description_1 = sa.Column(sa.String)
    email_1 = sa.Column(sa.String)
    day_phone_1 = sa.Column(sa.String)
    evening_phone_1 = sa.Column(sa.String)

    hs_contact_id = sa.Column(sa.String, nullable=False, unique=True)
    email_last_validated = sa.Column(sa.Date, nullable=False)
