#!/bin/bash

set -ex

PROJECT="${PROJECT:-DataLake}"

FUNCTIONS="${PROJECT}-Scheduler-sbx
           ${PROJECT}-DAG-Processor-sbx
           ${PROJECT}-Task-Processor-sbx"

for FUNCTION in ${FUNCTIONS}; do
  aws lambda update-function-code --function-name $FUNCTION --s3-bucket ama-hsg-datalabs-lambda-code-sandbox --s3-key CPT/CPT.zip || exit $?
  # aws --no-verify-ssl lambda update-function-code --function-name $FUNCTION --s3-bucket ama-hsg-datalabs-lambda-code-sandbox --s3-key CPT/CPT.zip || exit $?
done
