#!/bin/bash

set -ex

PROJECT="${PROJECT:-DataLake}"
ENVIRONMENT="${ENVIRONMENT:-sbx}"

CODE_BUCKET="ama-${ENVIRONMENT}-datalake-lambda-us-east-1"
FUNCTIONS=(
    "${PROJECT}-Scheduler-${ENVIRONMENT}"
    "${PROJECT}-DAG-Processor-${ENVIRONMENT}"
    "${PROJECT}-Task-Processor-${ENVIRONMENT}"
)
BUNDLES=(
    "${PROJECT}.zip"
    "${PROJECT}.zip"
    "${PROJECT}.zip"
)

for index in "${!FUNCTIONS[@]}"; do
  aws lambda update-function-code --function-name ${FUNCTIONS[index]} --s3-bucket ${CODE_BUCKET} --s3-key ${BUNDLES[index]} || exit $?
done
