#!/bin/bash

set -ex

PROJECT="${PROJECT:-DataLake}"
ENVIRONMENT="${ENVIRONMENT:-sbx}"

CODE_BUCKET="ama-${ENVIRONMENT}-datalake-lambda-us-east-1"
FUNCTIONS=(
    "${PROJECT}-${ENVIRONMENT}-Scheduler"
    "${PROJECT}-${ENVIRONMENT}-DAGProcessor"
    "${PROJECT}-${ENVIRONMENT}-TaskProcessor"
)
BUNDLES=(
    "Scheduler.zip"
    "Scheduler.zip"
    "Scheduler.zip"
)

for index in "${!FUNCTIONS[@]}"; do
  aws lambda update-function-code --function-name ${FUNCTIONS[index]} --s3-bucket ${CODE_BUCKET} --s3-key ${BUNDLES[index]} || exit $?
done
