import os

import jaydebeapi

aims = jaydebeapi.connect(
  'com.ibm.db2.jcc.DB2Jcc',
  'jdbc:db2://rdbp1190.ama-assn.org:54050/prddm',
  ['dlabs', os.getenv('JDBC_PASSWORD')],
  ['./db2jcc4.jar']
)

query = \
'''
SELECT DISTINCT O.FACT_EPROFILE_KEY, O.ORDER_NBR, O.CUSTOMER_KEY, O.ORDER_PRODUCT_ID, O.QUANTITY, H.MED_EDU_NBR, H.UPIN_NBR, D.FULL_DT
FROM AMADM.DIM_DATE D, AMADM.FACT_EPROFILE_ORDERS O, AMADM.DIM_PHYSICIAN_HIST H
WHERE D.DATE_KEY = O.ORDER_DT_KEY AND H.PHYSICIAN_HIST_KEY = O.ORDER_PHYSICIAN_HIST_KEY AND D.YR = '2003'
ORDER BY FACT_EPROFILE_KEY
'''

'''
SELECT DISTINCT D.YR as year
FROM AMADM.DIM_DATE D, AMADM.FACT_EPROFILE_ORDERS O, AMADM.DIM_PHYSICIAN_HIST H
WHERE D.DATE_KEY = O.ORDER_DT_KEY AND H.PHYSICIAN_HIST_KEY = O.ORDER_PHYSICIAN_HIST_KEY
ORDER BY D.YR
'''

'''
SELECT DISTINCT O.FACT_EPROFILE_KEY, O.ORDER_NBR, O.CUSTOMER_KEY, O.ORDER_PRODUCT_ID, O.QUANTITY, H.MED_EDU_NBR, H.UPIN_NBR, D.FULL_DT
FROM AMADM.DIM_DATE D, AMADM.FACT_EPROFILE_ORDERS O, AMADM.DIM_PHYSICIAN_HIST H
WHERE D.DATE_KEY = O.ORDER_DT_KEY AND H.PHYSICIAN_HIST_KEY = O.ORDER_PHYSICIAN_HIST_KEY AND D.YR = '2014'
ORDER BY FACT_EPROFILE_KEY
'''

'''
SELECT D.YR, COUNT(O.FACT_EPROFILE_KEY)
FROM AMADM.DIM_DATE D, AMADM.FACT_EPROFILE_ORDERS O
WHERE D.DATE_KEY = O.ORDER_DT_KEY
GROUP BY D.YR
'''
'''[(2003, 3), (2014, 59), (2015, 128883), (2016, 609488), (2017, 628499), (2018, 609498), (2019, 633371), (2020, 604330), (2021, 523054)]'''

'''
SELECT DISTINCT D.YR
FROM AMADM.DIM_DATE D, AMADM.FACT_EPROFILE_ORDERS O, AMADM.DIM_PHYSICIAN_HIST H
WHERE D.DATE_KEY = O.ORDER_DT_KEY AND H.PHYSICIAN_HIST_KEY = O.ORDER_PHYSICIAN_HIST_KEY
ORDER BY D.YR
'''
'''[(2021,), (2020,), (2019,), (2018,), (2017,), (2016,), (2015,), (2014,), (2003,)]'''

'''
SELECT DISTINCT O.FACT_EPROFILE_KEY, O.ORDER_NBR, O.CUSTOMER_KEY, O.ORDER_PRODUCT_ID, O.QUANTITY, H.MED_EDU_NBR, H.UPIN_NBR, D.FULL_DT
FROM AMADM.DIM_DATE D, AMADM.FACT_EPROFILE_ORDERS O, AMADM.DIM_PHYSICIAN_HIST H
WHERE D.DATE_KEY = O.ORDER_DT_KEY AND H.PHYSICIAN_HIST_KEY = O.ORDER_PHYSICIAN_HIST_KEY
ORDER BY FACT_EPROFILE_KEY
LIMIT 0, 1000
'''

'''
SELECT O.FACT_EPROFILE_KEY, O.ORDER_NBR, O.CUSTOMER_KEY, O.ORDER_PRODUCT_ID, O.QUANTITY, H.MED_EDU_NBR, H.UPIN_NBR, D.FULL_DT FROM AMADM.DIM_DATE D, AMADM.FACT_EPROFILE_ORDERS O, AMADM.DIM_PHYSICIAN_HIST H DISTINCT ON (O.FACT_EPROFILE_KEY, O.ORDER_NBR) WHERE D.DATE_KEY = O.ORDER_DT_KEY AND H.PHYSICIAN_HIST_KEY = O.ORDER_PHYSICIAN_HIST_KEY ORDER BY FACT_EPROFILE_KEY LIMIT 0, 1000;
'''
'''
SELECT count(O.FACT_EPROFILE_KEY), count(O.ORDER_NBR), count(O.CUSTOMER_KEY), count(O.ORDER_PRODUCT_ID), count(O.QUANTITY), count(H.MED_EDU_NBR), count(H.UPIN_NBR), count(D.FULL_DT)
FROM AMADM.DIM_DATE D, AMADM.FACT_EPROFILE_ORDERS O, AMADM.DIM_PHYSICIAN_HIST H
WHERE D.DATE_KEY = O.ORDER_DT_KEY AND H.PHYSICIAN_HIST_KEY = O.ORDER_PHYSICIAN_HIST_KEY
'''
'''
SELECT DISTINCT O.FACT_EPROFILE_KEY, O.ORDER_NBR, O.CUSTOMER_KEY, O.ORDER_PRODUCT_ID, O.QUANTITY, H.MED_EDU_NBR, H.UPIN_NBR, D.FULL_DT FROM AMADM.DIM_DATE D, AMADM.FACT_EPROFILE_ORDERS O, AMADM.DIM_PHYSICIAN_HIST H WHERE D.DATE_KEY = O.ORDER_DT_KEY AND H.PHYSICIAN_HIST_KEY = O.ORDER_PHYSICIAN_HIST_KEY LIMIT 0, 1000000;
'''
curs = aims.cursor()
curs.execute(query)
results = curs.fetchall()
print(results)
