import os

import jaydebeapi

aims = jaydebeapi.connect(
  'com.ibm.db2.jcc.DB2Jcc',
  'jdbc:db2://rdbp1190.ama-assn.org:54000/prddw',
  [os.getenv('JDBC_USERNAME'), os.getenv('JDBC_PASSWORD')],
  ['./db2jcc4.jar']
)

query = \
'''
SELECT FIPS_CD,DESCRIPTION,STATE_CD FROM AMAEDW.COUNTY_ZR WHERE FIPS_CD='02063'
'''
'''
SELECT ACTIVE_IND,AREA,AVG_HOUSE_VAL,AVG_INCOME,BLACK_NBR,CNTY_NAME_TYPE,COUNTY_SEAT,COUNTY_TYPE,DESCRIPTION,ELEVATION,FIPS_CD,HISP_NBR,HSEHLD_NBR,OPT_LOCK,POPULATION,PPH_NBR,STATE_CD,TIME_ZONE,UPDATE_DTM,UPDATE_USER_ID,WHITE_NBR FROM AMAEDW.COUNTY_ZR LIMIT 100
'''
'''
SELECT * FROM AMAEDW.COUNTY_ZR WHERE 
'''

'''
SELECT NAME FROM SYSIBM.SYSCOLUMNS WHERE TBNAME='COUNTY_ZR'
'''
'''
[('ACTIVE_IND',), ('AREA',), ('AVG_HOUSE_VAL',), ('AVG_INCOME',), ('BLACK_NBR',), ('CNTY_NAME_TYPE',), ('COUNTY_SEAT',), ('COUNTY_TYPE',), ('DESCRIPTION',), ('ELEVATION',), ('FIPS_CD',), ('HISP_NBR',), ('HSEHLD_NBR',), ('OPT_LOCK',), ('POPULATION',), ('PPH_NBR',), ('STATE_CD',), ('TIME_ZONE',), ('UPDATE_DTM',), ('UPDATE_USER_ID',), ('WHITE_NBR',)]
'''

curs = aims.cursor()
curs.execute(query)
results = curs.fetchall()
# print("ACTIVE_IND,AREA,AVG_HOUSE_VAL,AVG_INCOME,BLACK_NBR,CNTY_NAME_TYPE,COUNTY_SEAT,COUNTY_TYPE,DESCRIPTION,ELEVATION,FIPS_CD,HISP_NBR,HSEHLD_NBR,OPT_LOCK,POPULATION,PPH_NBR,STATE_CD,TIME_ZONE,UPDATE_DTM,UPDATE_USER_ID,WHITE_NBR")
print(results)
