apiVersion: v1
kind: ConfigMap
metadata:
    name: airflow-scheduler
    namespace: hsg-data-labs-dev
data:
    AIRFLOW_GPL_UNIDECODE: 'yes'
    AIRFLOW_HOME: /home/airflow
    AIRFLOW__CORE__DAGS_FOLDER: /home/airflow/repo/hs-datalabs/Source/Python/datalabs/airflow/dag
    AIRFLOW__CORE__DEFAULT_IMPERSONATION: '1000130000'
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__CORE__HOSTNAME_CALLABLE: socket.gethostname
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: Source/Python/datalabs/dag
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: 'False'
    AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: airflow-scheduler
    AIRFLOW__KUBERNETES__FS_GROUP: '1000130000'
    AIRFLOW__KUBERNETES__IN_CLUSTER: 'True'
    AIRFLOW__KUBERNETES__NAMESPACE: hsg-data-labs-dev
    AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: /home/airflow/worker.yaml
    AIRFLOW__KUBERNETES__RUN_AS_USER: '1000130000'
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: docker-registry.default.svc:5000/hsg-data-labs-dev/airflow-worker
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 1.0.4
    AIRFLOW__LOGGING__LOGGING_LEVEL: WARN
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: '60'
    AIRFLOW__WEBSERVER__RBAC: 'True'
