apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scheduled-job-poc
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:             
    spec:
      template:
        spec:
          containers:
          - command:
            - /ScheduledJobPoC/entrypoint.sh
            args:
            # - /bin/bash
            # - -c
            # - --
            # - "while true; do sleep 30; done;"
            - python
            - put_foo.py
            image: >-
              docker-registry.default.svc:5000/hsg-data-labs-dev/scheduled-job-poc
            imagePullPolicy: Always
            name: scheduled-job-poc
          restartPolicy: Never
