"""Oneview Physician Table Columns"""
columns = {
    'ME_NUMBER': 'medical_education_number',
    'ADDRESS_TYPE': 'address_type',
    'MAILING_NAME': 'mailing_name',
    'LAST_NAME': 'last_name',
    'FIRST_NAMES': 'first_name',
    'MIDDLE_NAME': 'middle_name',
    'SUFFIX_CODE': 'name_suffix',
    'PREFERRED_ADDR2': 'preferred_address_2',
    'PREFERRED_ADDR1': 'preferred_address_1',
    'PREFERRED_CITY': 'city',
    'PREFERRED_STATE': 'state',
    'PREFERRED_ZIP': 'zipcode',
    'PREFERRED_PLUS4': 'sector',
    'PREFERRED_CARRIERROUTE': 'carrier_route',
    'UNDELIVER_FLAG': 'address_undeliverable',
    'FIPS_county': 'federal_information_processing_standard_county',
    'FIPS_state': 'federal_information_processing_standard_state',
    'PRINTER_CONTROLCODE_BEGIN': 'printer_control_code_begin',
    'BARCODE_ZIP': 'barcode_zipcode',
    'BARCODE_PLUS4': 'barcode_zipcode_plus_4',
    'DELIVERYPOINTCODE': 'delivery_point',
    'CHECKDIGIT': 'check_digit',
    'PRINTER_CONTROLCODE_END': 'printer_control_code_end',
    'REGION': 'region',
    'DIVISION': 'division',
    'GROUP': 'group',
    'TRACT': 'tract',
    'SUFFIX': 'suffix',
    'BLOCKGROUP': 'block_group',
    'MSA_POPULATION': 'metropolitan_statistical_area_population',
    'MICRO_METRO_IND': 'micro_metro_indicator',
    'CBSA': 'core_based_statistical_area',
    'CBSA_DIVISION': 'core_based_statistical_area_division',
    'DEGREE_TYPE': 'degree_type',
    'BIRTH_YEAR': 'birth_year',
    'BIRTH_CITY': 'birth_city',
    'BIRTH_STATE': 'birth_state',
    'BIRTH_COUNTRY': 'birth_country',
    'GENDER': 'gender',
    'PREFERREDPHONENUMBER': 'telephone_number',
    'PENDINGDEAD_IND': 'presumed_dead',
    'FAXNUMBER': 'fax_number',
    'TOPCODE': 'type_of_practice_code',
    'PECODE': 'present_employment',
    'PRIMSPECIALTY': 'primary_specialty',
    'SECONDARYSPECIALTY': 'secondary_specialty',
    'MPACODE': 'major_professional_activity',
    'PRAAWARDRECIPIENT': 'physician_recognition_award_recipient',
    'PRAEXPIRATIONDATE': 'physician_recognition_award_expiration_date',
    'GMECONFIRMFLAG': 'graduate_medical_education_confirmed',
    'FROMDATE': 'from_date',
    'ENDDATE': 'end_date',
    'YEARINPROGRAM': 'year_in_program',
    'POSTGRADYEAR': 'post_graduate_year',
    'GMEPRIMSPECIALTY': 'graduate_medical_education_primary_specialty',
    'GMESECSPECIALTY': 'graduate_medical_education_secondary_specialty',
    'TRAINING_TYPE': 'training_type',
    'GMEHOSPITALSTATE': 'graduate_medical_education_hospital_state',
    'GMEHOSPITALID': 'graduate_medical_education_hospital',
    'GRADSCHOOLSTATE': 'medical_school_state',
    'GRADSCHOOLCODE': 'medical_school',
    'GRADYEAR': 'medical_school_graduation_year',
    'NOCONTACT_IND': 'no_contact_type',
    'NOWEBIND': 'no_web',
    'PDRP_FLAG': 'physician_data_restriction_program',
    'PDRP_DATE': 'physician_data_restriction_program_date',
    'POLO_ADDR2': 'polo_address_2',
    'POLO_ADDR1': 'polo_address_1',
    'POLO_CITY': 'polo_city',
    'POLO_STATE': 'polo_state',
    'POLO_ZIP': 'polo_zipcode',
    'POLO_PLUS4': 'polo_sector',
    'POLOCARRIERROUTE': 'polo_carrier_route',
    'MOSTRECENTFORMERLASTNAME': 'most_recent_former_last_name',
    'MOSTRECENTFORMERMIDDLENAME': 'most_recent_former_middle_name',
    'MOSTRECENTFORMERFIRSTNAME': 'most_recent_former_first_name',
    'NEXTMOSTRECENTFORMERLASTNAME': 'next_most_recent_former_last_name',
    'NEXTMOSTRECENTFORMERMIDDLENAME': 'next_most_recent_former_middle_name',
    'NEXTMOSTRECENTFORMERFIRSTNAME': 'next_most_recent_former_first_name'
}

names = ['ME_NUMBER', 'ADDRESS_TYPE', 'MAILING_NAME',
         'LAST_NAME', 'FIRST_NAME', 'MIDDLE_NAME', 'SUFFIX_CODE',
         'PREFERRED_ADDR2', 'PREFERRED_ADDR1', 'PREFERRED_CITY',
         'PREFERRED_STATE', 'PREFERRED_ZIP', 'PREFERRED_PLUS4',
         'PREFERRED_CARRIERROUTE', 'UNDELIVER_FLAG', 'FIPS_COUNTY', 'FIPS_STATE',
         'PRINTER_CONTROLCODE_BEGIN', 'BARCODE_ZIP', 'BARCODE_PLUS4',
         'DELIVERYPOINTCODE', 'CHECKDIGIT', 'PRINTER_CONTROLCODE_END', 'REGION',
         'DIVISION', 'GROUP', 'TRACT', 'SUFFIX', 'BLOCKGROUP', 'MSA_POPULATION',
         'MICRO_METRO_IND', 'CBSA', 'CBSA_DIVISION', 'DEGREE_TYPE', 'BIRTH_YEAR',
         'BIRTH_CITY', 'BIRTH_STATE', 'BIRTH_COUNTRY', 'GENDER',
         'PREFERREDPHONENUMBER', 'PENDINGDEAD_IND', 'FAXNUMBER', 'TOPCODE',
         'PECODE', 'PRIMSPECIALTY', 'SECONDARYSPECIALTY', 'MPACODE',
         'PRAAWARDRECIPIENT', 'PRAEXPIRATIONDATE', 'GMECONFIRMFLAG', 'FROMDATE',
         'ENDDATE', 'YEARINPROGRAM', 'POSTGRADYEAR', 'GMEPRIMSPECIALTY',
         'GMESECSPECIALTY', 'TRAINING_TYPE', 'GMEHOSPITALSTATE', 'GMEHOSPITALID',
         'GRADSCHOOLSTATE', 'GRADSCHOOLCODE', 'GRADYEAR', 'NOCONTACT_IND',
         'NOWEBIND', 'PDRP_FLAG', 'PDRP_DATE', 'POLO_ADDR2', 'POLO_ADDR1',
         'POLO_CITY', 'POLO_STATE', 'POLO_ZIP', 'POLO_PLUS4', 'POLOCARRIERROUTE',
         'MOSTRECENTFORMERLASTNAME', 'MOSTRECENTFORMERMIDDLENAME',
         'MOSTRECENTFORMERFIRSTNAME', 'NEXTMOSTRECENTFORMERLASTNAME',
         'NEXTMOSTRECENTFORMERMIDDLENAME', 'NEXTMOSTRECENTFORMERFIRSTNAME']
