TABLE_SAMPLE_COLUMNS = [
    'sample_id',
    'row_id',
    'sample_date',
    'me',
    'last_name',
    'first_name',
    'middle_name',
    'medschool_grad_year',
    'medschool_name',
    'degree_type',
    'specialty',
    'polo_city',
    'polo_state',
    'polo_zip',
    'lic_state',
    'lic_nbr',
    'oldphone1',
    'oldphone2',
    'oldphone3',
    'oldphone4',
    'oldphone5',
    'oldphone6',
    'oldphone7',
    'oldphone8',
    'oldphone9',
    'oldphone10',
    'oldphone11',
    'oldphone12',
    'oldphone13'
]

FILE_SAMPLE_COLUMNS = [
    'SAMPLE_ID',
    'ROW_ID',
    'LAST_NAME',
    'FIRST_NAME',
    'MIDDLE_NAME',
    'MEDSCHOOL_GRAD_YEAR',
    'MEDSCHOOL_NAME',
    'degree_type',
    'specialty',
    'POLO_CITY',
    'POLO_STATE',
    'POLO_ZIP',
    'lic_state',
    'lic_nbr',
    'oldphone1',
    'oldphone2',
    'oldphone3',
    'oldphone4',
    'oldphone5',
    'oldphone6',
    'oldphone7',
    'oldphone8',
    'oldphone9',
    'oldphone10',
    'oldphone11',
    'oldphone12',
    'oldphone13'
]

FILE_RESULT_COLUMNS = [
    'SAMPLE_ID',
    'ROW_ID',
    'LAST_NAME',
    'FIRST_NAME',
    'MIDDLE_NAME',
    'MEDSCHOOL_GRAD_YEAR',
    'MEDSCHOOL_NAME',
    'degree_type',
    'specialty',
    'POLO_CITY',
    'POLO_STATE',
    'POLO_ZIP',
    'lic_state',
    'lic_nbr',
    'OFFICE 1 PHONE NUMBER - GENERAL',
    'OFFICE 1 FAX NUMBER',
    'OFFICE 1 EMAIL',
    'Notes for AMA'
]

TABLE_RESULTS_COLUMNS = [c.lower() for c in FILE_RESULT_COLUMNS]
